Repository akka/akka-http, pull requests merged in 2018-06, with the labels that each got.

#2044 Test Set-Cookie header parsing with extra quotes
  akka-http-core/src/test/scala/akka/http/impl/engine/parsing/HttpHeaderParserSpec.scala
Labels: tested

#2045 Upgrade to sbt 1.1.6
  project/build.properties
Labels: tested

#2047 =pro Update specs and gson dependencies
  project/Dependencies.scala
Labels: tested

#2046 [backport from master] Upgrade to sbt 1.1.6
  project/build.properties
Labels: tested

#2029 Added ability to set https proxy host and port through application.conf
  akka-http-core/src/main/resources/reference.conf
  akka-http-core/src/main/scala/akka/http/impl/settings/HttpsProxySettingsImpl.scala
  akka-http-core/src/main/scala/akka/http/javadsl/ClientTransport.scala
  akka-http-core/src/main/scala/akka/http/javadsl/settings/HttpsProxySettings.scala
  akka-http-core/src/main/scala/akka/http/scaladsl/ClientTransport.scala
  akka-http-core/src/main/scala/akka/http/scaladsl/settings/HttpsProxySettings.scala
  akka-http-core/src/test/scala/akka/http/impl/engine/client/HttpConfigurationSpec.scala
  docs/src/main/paradox/client-side/client-transport.md
Labels: tested

#2049 Backport: Fix type parameters in Java API to work with latest Akka #1965
  akka-http-core/src/main/java/akka/http/javadsl/model/Multiparts.java
  akka-http-core/src/main/scala/akka/http/scaladsl/model/Multipart.scala
  akka-http-testkit/src/main/scala/akka/http/javadsl/testkit/WSProbe.scala
  akka-http-testkit/src/main/scala/akka/http/javadsl/testkit/WSTestRequestBuilding.scala
Labels: tested

#2035 "Graceful" Server Termination #188
  akka-http-core/src/main/mima-filters/10.1.2.backwards.excludes
  akka-http-core/src/main/resources/reference.conf
  akka-http-core/src/main/scala/akka/http/impl/engine/server/HttpServerBluePrint.scala
  akka-http-core/src/main/scala/akka/http/impl/engine/server/ServerTerminator.scala
  akka-http-core/src/main/scala/akka/http/impl/settings/ServerSettingsImpl.scala
  akka-http-core/src/main/scala/akka/http/javadsl/ServerBinding.scala
  akka-http-core/src/main/scala/akka/http/javadsl/settings/ServerSettings.scala
  akka-http-core/src/main/scala/akka/http/scaladsl/Http.scala
  akka-http-core/src/main/scala/akka/http/scaladsl/settings/ServerSettings.scala
  akka-http-core/src/test/java/akka/http/javadsl/GracefulTerminationCompileTest.java
  akka-http-core/src/test/scala/akka/http/impl/engine/client/ConnectionPoolSpec.scala
  akka-http-core/src/test/scala/akka/http/scaladsl/GracefulTerminationSpec.scala
  akka-http2-support/src/main/scala/akka/http/scaladsl/Http2.scala
Labels: tested

#2030 Re-enabled OSGi support (#1852).
  akka-http-osgi-tests/README.md
  akka-http-osgi-tests/src/test/scala/akka/http/test/osgi/OsgiSanitySpec.scala
  build.sbt
  project/Dependencies.scala
  project/OSGi.scala
  project/plugins.sbt
Labels: 2 - pick next, tested

#2026 Adds missing parameter with required value directive for Java API (#2025)
  akka-http-tests/src/test/java/akka/http/javadsl/server/directives/ParameterDirectivesTest.java
  akka-http-tests/src/test/scala/akka/http/scaladsl/server/directives/ParameterDirectivesSpec.scala
  akka-http/src/main/scala/akka/http/javadsl/server/Rejections.scala
  akka-http/src/main/scala/akka/http/javadsl/server/directives/ParameterDirectives.scala
  akka-http/src/main/scala/akka/http/scaladsl/server/Rejection.scala
  akka-http/src/main/scala/akka/http/scaladsl/server/RejectionHandler.scala
  akka-http/src/main/scala/akka/http/scaladsl/server/directives/ParameterDirectives.scala
  docs/src/main/paradox/routing-dsl/directives/parameter-directives/parameters.md
  docs/src/test/java/docs/http/javadsl/server/directives/ParameterDirectivesExamplesTest.java
  docs/src/test/scala/docs/http/scaladsl/server/directives/ParameterDirectivesExamplesSpec.scala
Labels: tested

#2058 Add release 10.1.2 release notes, update to Akka 2.5.13
  RELEASING.md
  docs/src/main/paradox/release-notes/10.1.x.md
Labels: tested

#2062 Fix link to compatibility rules section
  docs/src/main/paradox/compatibility-guidelines.md
  docs/src/main/paradox/migration-guide/migration-guide-10.0.x.md
  docs/src/main/paradox/routing-dsl/HttpApp.md
  docs/src/main/paradox/routing-dsl/index.md
Labels: tested

#2059 doc Correct pipelining-limit flag name
  docs/src/main/paradox/server-side/low-level-api.md
Labels: tested

#2056 Fix 404 not found on Source Streaming.
  docs/src/main/paradox/common/json-support.md
Labels: tested

#2063 More descriptive error message for actorSystem
  akka-http-core/src/main/scala/akka/http/impl/util/package.scala
Labels: tested

#2068 improve caching code sample
  docs/src/main/paradox/common/caching.md
  docs/src/test/java/docs/http/javadsl/server/directives/CachingDirectivesExamplesTest.java
  docs/src/test/scala/docs/http/scaladsl/server/directives/CachingDirectivesExamplesSpec.scala
Labels: tested

#2070 =htc #2067 fix memory leak in server terminators
  akka-http-core/src/main/scala/akka/http/impl/engine/server/ServerTerminator.scala
  akka-http-core/src/main/scala/akka/http/scaladsl/Http.scala
Labels: tested

#2072 +doc docs for graceful termination
  akka-http-core/src/main/scala/akka/http/javadsl/ServerBinding.scala
  akka-http-core/src/main/scala/akka/http/scaladsl/Http.scala
  docs/src/main/paradox/server-side/graceful-termination.md
  docs/src/main/paradox/server-side/index.md
  docs/src/test/java/docs/http/javadsl/server/HttpServerExampleDocTest.java
  docs/src/test/scala/docs/http/scaladsl/HttpServerExampleSpec.scala
Labels: t:docs, tested

#2069 Avoid eagerly failing connections when request closes
  akka-http-core/src/main/scala/akka/http/impl/engine/server/ServerTerminator.scala
  akka-http-core/src/test/scala/akka/http/scaladsl/ClientServerSpec.scala
Labels: tested

#2077 release notes for 10.1.3
  docs/src/main/paradox/release-notes/10.1.x.md
  docs/src/test/java/docs/http/javadsl/server/HttpServerExampleDocTest.java
  docs/src/test/scala/docs/http/scaladsl/HttpServerExampleSpec.scala
Labels: tested

#2074 Fix some warnings
  akka-http-caching/src/main/scala/akka/http/javadsl/server/directives/CachingDirectives.scala
  akka-http-core/src/main/scala/akka/http/impl/engine/client/pool/SlotState.scala
  akka-http-core/src/main/scala/akka/http/javadsl/ConnectionContext.scala
  akka-http-core/src/main/scala/akka/http/scaladsl/ClientTransport.scala
  akka-http-core/src/main/scala/akka/http/scaladsl/Http.scala
  akka-http-core/src/test/scala/akka/http/impl/engine/client/ConnectionPoolSpec.scala
  akka-http-core/src/test/scala/akka/http/impl/engine/client/HostConnectionPoolSpec.scala
  akka-http-core/src/test/scala/akka/http/impl/engine/client/LowLevelOutgoingConnectionSpec.scala
  akka-http-core/src/test/scala/akka/http/impl/engine/client/pool/SlotStateSpec.scala
  akka-http-core/src/test/scala/akka/http/scaladsl/GracefulTerminationSpec.scala
  akka-http-core/src/test/scala/akka/http/scaladsl/settings/PreviewServerSettingsSpec.scala
  akka-http-core/src/test/scala/akka/http/scaladsl/util/FastFutureSpec.scala
  akka-http-tests/src/multi-jvm/scala/akka/http/AkkaHttpServerLatencyMultiNodeSpec.scala
  akka-http-tests/src/multi-jvm/scala/akka/remote/testkit/MultiNodeConfig.scala
  akka-http-tests/src/test/scala/akka/http/javadsl/server/HttpAppSpec.scala
  akka-http-tests/src/test/scala/akka/http/scaladsl/CustomMediaTypesSpec.scala
  akka-http-tests/src/test/scala/akka/http/scaladsl/server/HttpAppSpec.scala
  akka-http-tests/src/test/scala/akka/http/scaladsl/server/directives/FileUploadDirectivesSpec.scala
  akka-http2-support/src/main/scala/akka/http/scaladsl/Http2.scala
  akka-http2-support/src/test/scala/akka/http/h2spec/H2SpecIntegrationSpec.scala
  akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2ServerSpec.scala
  akka-http2-support/src/test/scala/akka/http/scaladsl/Http2BindingViaConfigSpec.scala
Labels: tested

#2082 Fix broken links at 10.1.x release notes
  docs/src/main/paradox/release-notes/10.1.x.md
Labels: tested

#2061 Add info in MiMa ignore section about @InternalApi and co
  CONTRIBUTING.md
Labels: tested

#2086 Provide issue template for project
  .github/ISSUE_TEMPLATE.md
Labels: tested

#2091 +htp #891 allow java/scala conversion for Routes for users
  akka-http-tests/src/test/java/docs/http/javadsl/server/RouteJavaScalaDslConversionTest.java
  akka-http-tests/src/test/scala/akka/http/scaladsl/RouteJavaScalaDslConversionSpec.scala
  akka-http/src/main/mima-filters/10.1.3.backwards.excludes
  akka-http/src/main/scala/akka/http/javadsl/server/Route.scala
  akka-http/src/main/scala/akka/http/javadsl/server/directives/RouteAdapter.scala
  docs/src/main/paradox/routing-dsl/routes.md
Labels: tested

#2053 remove misplaced directives
  akka-http-core/src/main/java/akka/http/javadsl/model/headers/ModeledCustomHeader.java
  docs/src/main/paradox/common/http-model.md
Labels: tested

#2095 Show off GenericMarshallers.futureMarshaller
  docs/src/test/scala/docs/http/scaladsl/server/directives/RouteDirectivesExamplesSpec.scala
Labels: tested

#2094 Fix links to RequestEntityExpectedRejection api documentation
  docs/src/main/paradox/routing-dsl/directives/alphabetically.md
  docs/src/main/paradox/routing-dsl/directives/marshalling-directives/entity.md
  docs/src/main/paradox/routing-dsl/directives/misc-directives/requestEntityPresent.md
Labels: tested

#2089 improve graceful shutdown behaviour #2090
  akka-http-core/src/main/scala/akka/http/impl/engine/server/ServerTerminator.scala
  akka-http-core/src/main/scala/akka/http/javadsl/ServerBinding.scala
  akka-http-core/src/main/scala/akka/http/scaladsl/Http.scala
  akka-http-core/src/test/scala/akka/http/scaladsl/GracefulTerminationSpec.scala
  docs/src/main/paradox/server-side/graceful-termination.md
Labels: tested

#2098 fix a little typo in marshalling.md
  docs/src/main/paradox/common/marshalling.md
Labels: tested
