Repository akka/akka-http, pull requests merged in 2018-03, with the labels that each got.

#1893 update akka version to 2.5.11 and fix docs #1892
  docs/src/main/paradox/server-side/server-https-support.md
  docs/src/main/paradox/server-side/websocket-support.md
  project/AkkaDependency.scala
Labels: tested

#1878 create internal actors in the system namespace
  akka-http-core/src/main/mima-filters/10.0.11.backwards.excludes
  akka-http-core/src/main/scala/akka/http/scaladsl/Http.scala
  akka-http-tests/src/test/scala/akka/http/scaladsl/TypedActorSystemSpec.scala
  build.sbt
Labels: tested

#1828 Ability to access current response timeout (#1811)
  akka-http-core/src/main/java/akka/http/javadsl/TimeoutAccess.java
  akka-http-core/src/main/mima-filters/10.0.11.backwards.excludes
  akka-http-core/src/main/scala/akka/http/impl/engine/server/HttpServerBluePrint.scala
  akka-http-core/src/main/scala/akka/http/scaladsl/TimeoutAccess.scala
  akka-http/src/main/mima-filters/10.0.11.backwards.excludes
  akka-http/src/main/scala/akka/http/javadsl/server/directives/TimeoutDirectives.scala
  akka-http/src/main/scala/akka/http/scaladsl/server/directives/TimeoutDirectives.scala
  docs/src/main/paradox/routing-dsl/directives/timeout-directives/extractRequestTimeout.md
  docs/src/test/java/docs/http/javadsl/server/directives/TimeoutDirectivesExamplesTest.java
  docs/src/test/scala/docs/http/scaladsl/server/directives/TimeoutDirectivesExamplesSpec.scala
Labels: 2 - pick next, tested

#1900 =htc #1757 create a new server binding for each new test to avoid interaction between test cases
  akka-http-core/src/test/scala/akka/http/impl/engine/client/HostConnectionPoolSpec.scala
Labels: tested

#1901 =ht2 don't fail any tests on jenkins for now to make tests blue
  akka-http2-support/src/test/scala/akka/http/h2spec/H2SpecIntegrationSpec.scala
Labels: tested

#1902 =htc #1886 add WithLogCapturing and log more in failure cases
  akka-http-core/src/test/scala/akka/http/scaladsl/ClientServerSpec.scala
Labels: tested

#1903 Allow linking to case objects with `@unidoc`
  docs/src/main/paradox/common/caching.md
  project/ParadoxSupport.scala
Labels: tested

#1894 Fix several warnings across the project
  akka-http-core/src/main/scala/akka/http/impl/engine/client/PoolConductor.scala
  akka-http-testkit/src/main/scala/akka/http/javadsl/testkit/RouteTest.scala
  akka-http-testkit/src/main/scala/akka/http/scaladsl/testkit/MarshallingTestUtils.scala
  akka-http-testkit/src/main/scala/akka/http/scaladsl/testkit/RouteTest.scala
  akka-http-tests/src/test/java/akka/http/javadsl/server/MarshallerTest.java
  akka-http/src/main/mima-filters/10.0.11.backwards.excludes
  akka-http/src/main/scala/akka/http/javadsl/server/Route.scala
  akka-http/src/main/scala/akka/http/javadsl/server/directives/RouteAdapter.scala
  akka-http/src/main/scala/akka/http/scaladsl/marshalling/PredefinedToResponseMarshallers.scala
  akka-http/src/main/scala/akka/http/scaladsl/server/directives/FileAndResourceDirectives.scala
  akka-http/src/main/scala/akka/http/scaladsl/server/directives/FileUploadDirectives.scala
  akka-http/src/main/scala/akka/http/scaladsl/server/directives/ParameterDirectives.scala
  akka-http/src/main/scala/akka/http/scaladsl/unmarshalling/sse/LineParser.scala
  akka-http2-support/src/main/scala/akka/http/impl/engine/http2/Http2ServerDemux.scala
  akka-http2-support/src/main/scala/akka/http/impl/engine/http2/PriorityTree.scala
  akka-http2-support/src/main/scala/akka/http/impl/engine/http2/hpack/HeaderCompression.scala
  akka-http2-support/src/main/scala/akka/http/impl/engine/http2/hpack/HeaderDecompression.scala
  docs/src/test/java/docs/http/javadsl/RouteSealExample.java
  docs/src/test/java/docs/http/javadsl/server/directives/SecurityDirectivesExamplesTest.java
Labels: 2 - pick next, tested

#1897 Mark a lot more internal classes as such
  akka-http-core/src/main/scala/akka/http/impl/engine/ws/Randoms.scala
  akka-http-core/src/main/scala/akka/http/impl/engine/ws/WebSocketClientBlueprint.scala
  akka-http-core/src/main/scala/akka/http/impl/model/JavaQuery.scala
  akka-http-core/src/main/scala/akka/http/impl/model/JavaUri.scala
  akka-http-core/src/main/scala/akka/http/impl/model/parser/Base64Parsing.scala
  akka-http-core/src/main/scala/akka/http/impl/util/ByteStringParserInput.scala
  akka-http-core/src/main/scala/akka/http/impl/util/JavaAccessors.scala
  akka-http-core/src/main/scala/akka/http/impl/util/StageLoggingWithOverride.scala
  akka-http2-support/src/main/scala/akka/http/impl/engine/http2/AlpnSwitch.scala
  akka-http2-support/src/main/scala/akka/http/impl/engine/http2/FrameEvent.scala
  akka-http2-support/src/main/scala/akka/http/impl/engine/http2/FrameLogger.scala
  akka-http2-support/src/main/scala/akka/http/impl/engine/http2/Http2Blueprint.scala
  akka-http2-support/src/main/scala/akka/http/impl/engine/http2/Http2Compliance.scala
  akka-http2-support/src/main/scala/akka/http/impl/engine/http2/Http2Multiplexer.scala
  akka-http2-support/src/main/scala/akka/http/impl/engine/http2/Http2ServerDemux.scala
  akka-http2-support/src/main/scala/akka/http/impl/engine/http2/Http2StreamHandling.scala
  akka-http2-support/src/main/scala/akka/http/impl/engine/http2/IncomingFlowController.scala
  akka-http2-support/src/main/scala/akka/http/impl/engine/http2/PriorityTree.scala
  akka-http2-support/src/main/scala/akka/http/impl/engine/http2/ResponseRendering.scala
  akka-http2-support/src/main/scala/akka/http/impl/engine/http2/StreamPrioritizer.scala
  akka-http2-support/src/main/scala/akka/http/impl/engine/http2/framing/FrameRenderer.scala
  akka-http2-support/src/main/scala/akka/http/impl/engine/http2/framing/Http2FrameParsing.scala
  akka-http2-support/src/main/scala/akka/http/impl/engine/http2/framing/Http2FrameRendering.scala
  akka-http2-support/src/main/scala/akka/http/impl/engine/http2/hpack/ByteStringInputStream.scala
  akka-http2-support/src/main/scala/akka/http/impl/engine/http2/hpack/HeaderCompression.scala
  akka-http2-support/src/main/scala/akka/http/impl/engine/http2/hpack/HeaderDecompression.scala
  akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2ServerSpec.scala
  akka-http2-support/src/test/scala/akka/http/impl/engine/http2/RequestParsingSpec.scala
  akka-http2-support/src/test/scala/akka/http/impl/engine/http2/framing/Http2FramingSpec.scala
  build.sbt
Labels: 2 - pick next, tested

#1906 =htc #1905 fix mima failure in 2.11
  akka-http-core/src/main/mima-filters/10.0.11.backwards.excludes
Labels: 2 - pick next, tested

#1909 =pro another round of dependency updates
  project/Dependencies.scala
Labels: tested

#1912 =pro also allow building for 2.13.0-M3
  project/Dependencies.scala
Labels: tested

#1913 =pro upgrade to genjavadoc 0.11 which has a 2.13.0-M3 version available
  project/Doc.scala
Labels: tested

#1910 List APIs that may change #1106
  akka-http-caching/src/main/scala/akka/http/scaladsl/server/directives/CachingDirectives.scala
  docs/src/main/paradox/compatibility-guidelines.md
  docs/src/test/scala/docs/ApiMayChangeDocCheckerSpec.scala
  project/Dependencies.scala
Labels: 2 - pick next, tested

#1904 Add javadoc generation for akka-http-caching
  build.sbt
Labels: tested

#1917 =pro fix javadoc generation
  akka-http-core/src/main/scala/akka/http/scaladsl/settings/ConnectionPoolSettings.scala
Labels: tested

#1920 =doc add release notes and migration guide for 10.1.0
  docs/src/main/paradox/compatibility-guidelines.md
  docs/src/main/paradox/migration-guide/index.md
  docs/src/main/paradox/migration-guide/migration-guide-10.1.x.md
  docs/src/main/paradox/release-notes/10.1.x.md
Labels: validating

#1918 Fix a few 2.13.0-M3 compilation issues
  akka-http-core/src/main/java/akka/http/impl/util/Util.java
  akka-http-core/src/main/scala/akka/http/impl/engine/parsing/HttpMessageParser.scala
  akka-http-core/src/main/scala/akka/http/impl/engine/parsing/ParserOutput.scala
  akka-http-core/src/main/scala/akka/http/impl/model/parser/UriParser.scala
Labels: tested

#1933 Add package name to `PathMatcher` javadsl docs
  docs/src/main/paradox/routing-dsl/path-matchers.md
Labels: tested

#1937 Always parse Content-Encoding and WebSocket headers
  akka-http-core/src/main/scala/akka/http/impl/engine/parsing/HttpHeaderParser.scala
Labels: needs-backport, play-akka-http-integration, tested

#1941 Always parse Content-Encoding and WebSocket headers (#1937)
  akka-http-core/src/main/scala/akka/http/impl/engine/parsing/HttpHeaderParser.scala
Labels: 2 - pick next, tested

#1944 Fix paradox error for discard entity bytes
  docs/src/main/paradox/client-side/request-level.md
Labels: tested

#1928 Remove not needed implicits from Route.seal #1898
  akka-http/src/main/scala/akka/http/javadsl/server/Route.scala
  akka-http/src/main/scala/akka/http/javadsl/server/directives/RouteAdapter.scala
  akka-http/src/main/scala/akka/http/scaladsl/server/Route.scala
Labels: reviewed, tested

#1947 Emit entity truncation errors before completing graph stage
  akka-http-core/src/main/scala/akka/http/impl/engine/client/OutgoingConnectionBlueprint.scala
  akka-http-core/src/test/scala/akka/http/impl/engine/client/ResponseParsingMergeSpec.scala
Labels: reviewed, tested

#1950 Support conversion between scaladsl.Uri and javadsl.Uri
  akka-http-core/src/main/java/akka/http/impl/util/Util.java
  akka-http-core/src/main/java/akka/http/javadsl/model/Uri.java
  akka-http-core/src/main/java/akka/http/javadsl/model/headers/LinkParams.java
  akka-http-core/src/main/java/akka/http/javadsl/model/headers/LinkValue.java
  akka-http-core/src/main/java/akka/http/javadsl/model/headers/Location.java
  akka-http-core/src/main/java/akka/http/javadsl/model/headers/Referer.java
  akka-http-core/src/main/mima-filters/10.1.0.backwards.excludes
  akka-http-core/src/main/scala/akka/http/impl/model/JavaUri.scala
Labels: tested

#1957 BACKPORT Support conversion between scaladsl.Uri and javadsl.Uri (#1950)
  akka-http-core/src/main/java/akka/http/impl/util/Util.java
  akka-http-core/src/main/java/akka/http/javadsl/model/Uri.java
  akka-http-core/src/main/java/akka/http/javadsl/model/headers/LinkParams.java
  akka-http-core/src/main/java/akka/http/javadsl/model/headers/LinkValue.java
  akka-http-core/src/main/java/akka/http/javadsl/model/headers/Location.java
  akka-http-core/src/main/java/akka/http/javadsl/model/headers/Referer.java
  akka-http-core/src/main/mima-filters/10.1.0.backwards.excludes
  akka-http-core/src/main/scala/akka/http/impl/model/JavaUri.scala
Labels: 2 - pick next, tested

#1958 BACKPORT Allows Sec-WebSocket-Extensions in requests
  akka-http-core/src/main/scala/akka/http/scaladsl/model/headers/headers.scala
  akka-http-core/src/test/scala/akka/http/scaladsl/model/headers/HeaderSpec.scala
Labels: 2 - pick next, tested

#1960 Revert "!pro make akka-actor / akka-stream a provided dependency (#1582)"
  build.sbt
  docs/src/main/paradox/compatibility-guidelines.md
  docs/src/main/paradox/introduction.md
Labels: tested

#1961 Always render the custom header from the example
  akka-http-tests/src/test/scala/akka/http/scaladsl/server/ModeledCustomHeaderSpec.scala
Labels: tested

#1962 =htc #1757 create a new server binding for each new test to avoid interaction between test cases
  akka-http-core/src/test/scala/akka/http/impl/engine/client/HostConnectionPoolSpec.scala
Labels: tested

#1956 Cache docs: more explicit imports, create cache once
  docs/src/test/java/docs/http/javadsl/server/directives/CachingDirectivesExamplesTest.java
  docs/src/test/scala/docs/http/scaladsl/server/directives/CachingDirectivesExamplesSpec.scala
Labels: tested

#1938 Transparent websocket ping/pong
  akka-http-core/src/main/mima-filters/10.1.0.backwards.excludes
  akka-http-core/src/main/resources/reference.conf
  akka-http-core/src/main/scala/akka/http/impl/engine/server/HttpServerBluePrint.scala
  akka-http-core/src/main/scala/akka/http/impl/engine/ws/FrameHandler.scala
  akka-http-core/src/main/scala/akka/http/impl/engine/ws/Protocol.scala
  akka-http-core/src/main/scala/akka/http/impl/engine/ws/WebSocket.scala
  akka-http-core/src/main/scala/akka/http/impl/engine/ws/WebSocketClientBlueprint.scala
  akka-http-core/src/main/scala/akka/http/impl/settings/ClientConnectionSettingsImpl.scala
  akka-http-core/src/main/scala/akka/http/impl/settings/ServerSettingsImpl.scala
  akka-http-core/src/main/scala/akka/http/impl/settings/WebSocketSettingsImpl.scala
  akka-http-core/src/main/scala/akka/http/impl/util/JavaMapping.scala
  akka-http-core/src/main/scala/akka/http/javadsl/settings/ClientConnectionSettings.scala
  akka-http-core/src/main/scala/akka/http/javadsl/settings/ServerSettings.scala
  akka-http-core/src/main/scala/akka/http/javadsl/settings/WebSocketSettings.scala
  akka-http-core/src/main/scala/akka/http/scaladsl/settings/ClientConnectionSettings.scala
  akka-http-core/src/main/scala/akka/http/scaladsl/settings/ServerSettings.scala
  akka-http-core/src/main/scala/akka/http/scaladsl/settings/WebSocketSettings.scala
  akka-http-core/src/test/scala/akka/http/impl/engine/ws/ByteStringSinkProbe.scala
  akka-http-core/src/test/scala/akka/http/impl/engine/ws/MessageSpec.scala
  akka-http-core/src/test/scala/akka/http/impl/engine/ws/WebSocketServerSpec.scala
  akka-http-core/src/test/scala/akka/http/impl/engine/ws/WithMaterializerSpec.scala
  akka-http-core/src/test/scala/akka/http/scaladsl/TestServer.scala
  docs/src/main/paradox/client-side/websocket-support.md
  docs/src/main/paradox/server-side/websocket-support.md
  docs/src/test/java/docs/http/javadsl/server/WebSocketCoreExample.java
  docs/src/test/scala/docs/http/scaladsl/server/WebSocketExampleSpec.scala
Labels: 1 - triaged, reviewed, tested

#1964 =doc document client-side for streaming JSON
  akka-http-tests/src/test/scala/akka/http/scaladsl/server/EntityStreamingSpec.scala
  docs/src/main/paradox/common/json-support.md
  docs/src/main/paradox/routing-dsl/source-streaming-support.md
  docs/src/test/java/docs/http/javadsl/server/JsonStreamingExamplesTest.java
Labels: 2 - pick next, t:docs, tested

#1967 Skip travis cleanup
  .travis.yml
Labels: tested
