Repository akka/akka-http, pull requests merged in 2019-09, with the labels that each got.

#2674 Call onResponseComplete when the response promise is completed
  akka-http-core/src/main/scala/akka/http/impl/engine/client/PoolInterface.scala
Labels: tested

#2677 docs: fix typed example not to fail against Akka 2.6 and/or Scala 2.11
  build.sbt
  docs/src/main/paradox/routing-dsl/index.md
  docs/src/test/scala-2.12+/docs/http/scaladsl/HttpServerWithTypedSpec.scala
  project/AkkaDependency.scala
Labels: tested

#2668 fix: akka-stream-testkit version
  docs/src/main/paradox/routing-dsl/testkit.md
Labels: tested

#2669 Update authenticateOAuth2.md
  docs/src/main/paradox/routing-dsl/directives/security-directives/authenticateOAuth2.md
Labels: tested

#2681 Clean up bintray package name
  notes/release-train-issue-template.md
  project/Publish.scala
Labels: tested

#2680 Always target java 8 bootclasspath
  build.sbt
  project/Common.scala
Labels: tested

#2683 xml: import constants from com.sun.org.apache.xerces.internal.impl.Constants
  akka-http-marshallers-scala/akka-http-xml/src/main/scala/akka/http/scaladsl/marshallers/xml/ScalaXmlSupport.scala
Labels: failed, tested

#2684 Switch to torkild credentials
  .travis.yml
Labels: tested

#2671 Bump up dependencies.
  project/AkkaDependency.scala
  project/Dependencies.scala
  project/plugins.sbt
Labels: tested

#2687 Temporary fix for Typed doc sample code
  docs/src/main/paradox/routing-dsl/index.md
  docs/src/test/scala-2.12+/docs/http/scaladsl/HttpServerWithTypedSpec.scala
Labels: tested

#2689 Add scala-steward config to exclude akka
  .scala-steward.conf
Labels: tested

#2688 CVE-2019-14439: bump jackson-databind to 2.9.9.3
  build.sbt
  project/Dependencies.scala
Labels: tested

#2632 http: fail eitherUnmarshaller when entity is not strict
  akka-http/src/main/scala/akka/http/scaladsl/unmarshalling/GenericUnmarshallers.scala
Labels: tested

#2512 Add logging unsupported content type
  akka-http-marshallers-scala/akka-http-spray-json/src/main/scala/akka/http/scaladsl/marshallers/sprayjson/SprayJsonSupport.scala
  akka-http-tests/src/test/scala/akka/http/scaladsl/marshallers/xml/ScalaXmlSupportSpec.scala
  akka-http-tests/src/test/scala/akka/http/scaladsl/server/EntityStreamingSpec.scala
  akka-http-tests/src/test/scala/akka/http/scaladsl/server/directives/MarshallingDirectivesSpec.scala
  akka-http/src/main/scala/akka/http/javadsl/server/Rejections.scala
  akka-http/src/main/scala/akka/http/javadsl/unmarshalling/Unmarshaller.scala
  akka-http/src/main/scala/akka/http/scaladsl/common/StrictForm.scala
  akka-http/src/main/scala/akka/http/scaladsl/server/Rejection.scala
  akka-http/src/main/scala/akka/http/scaladsl/server/RejectionHandler.scala
  akka-http/src/main/scala/akka/http/scaladsl/server/directives/FormFieldDirectives.scala
  akka-http/src/main/scala/akka/http/scaladsl/server/directives/FramedEntityStreamingDirectives.scala
  akka-http/src/main/scala/akka/http/scaladsl/server/directives/MarshallingDirectives.scala
  akka-http/src/main/scala/akka/http/scaladsl/unmarshalling/MultipartUnmarshallers.scala
  akka-http/src/main/scala/akka/http/scaladsl/unmarshalling/Unmarshaller.scala
  docs/src/test/scala/docs/http/scaladsl/server/directives/JsonStreamingExamplesSpec.scala
Labels: tested

#2540 Add modeled header for Content-Location
  akka-http-core/src/main/java/akka/http/javadsl/model/headers/ContentLocation.java
  akka-http-core/src/main/mima-filters/10.1.9.backwards.excludes/pr-2540-add-content-location-header-model.excludes
  akka-http-core/src/main/scala/akka/http/impl/model/parser/HeaderParser.scala
  akka-http-core/src/main/scala/akka/http/impl/model/parser/SimpleHeaders.scala
  akka-http-core/src/main/scala/akka/http/scaladsl/model/headers/headers.scala
  akka-http-core/src/test/scala/akka/http/impl/model/parser/HttpHeaderSpec.scala
Labels: tested

#2693 Update sbt-paradox to 0.6.4
  project/plugins.sbt
Labels: tested

#2509 Make sure that MediaType is lowercase automatically
  akka-http-core/src/main/mima-filters/10.1.9.backwards.excludes/pr-2509-ensure-lower-case-media-types.excludes
  akka-http-core/src/main/scala/akka/http/scaladsl/model/MediaType.scala
  akka-http-core/src/test/scala/akka/http/impl/engine/parsing/RequestParserSpec.scala
  akka-http-tests/src/test/scala/akka/http/scaladsl/unmarshalling/UnmarshallingSpec.scala
Labels: tested

#2698 Update sbt-whitesource to 0.1.17
  project/plugins.sbt
Labels: tested

#2686 Disallow entity for 205 status code
  akka-http-core/src/main/scala/akka/http/scaladsl/model/StatusCode.scala
  docs/src/main/paradox/release-notes/10.1.x.md
Labels: tested

#2699 Update sbt-paradox to 0.6.5
  project/ParadoxSupport.scala
  project/plugins.sbt
Labels: tested

#2704 Update sbt-paradox-apidoc to 0.3
  project/plugins.sbt
Labels: tested

#2703 build: Update sbt-paradox-akka to 0.24
  project/plugins.sbt
Labels: tested

#2706 http2: backpressure incoming frames when too many outgoing control frames are buffered
  akka-http-core/src/main/mima-filters/10.1.9.backwards.excludes/pr-2706-add-http2-setting-outgoing-control-frame-buffer-size.excludes
  akka-http-core/src/main/resources/reference.conf
  akka-http-core/src/main/scala/akka/http/javadsl/settings/Http2ServerSettings.scala
  akka-http-core/src/main/scala/akka/http/scaladsl/settings/Http2ServerSettings.scala
  akka-http2-support/src/main/scala/akka/http/impl/engine/http2/Http2Multiplexer.scala
  akka-http2-support/src/main/scala/akka/http/impl/engine/http2/Http2ServerDemux.scala
  akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2ServerSpec.scala
Labels: 2 - pick next, tested

#2464 Support HTTP2 in cleartext (h2c) via Upgrade from HTTP1
  akka-http-core/src/main/mima-filters/10.1.9.backwards.excludes/issue-4849-h2c-upgrade
  akka-http-core/src/main/scala/akka/http/impl/engine/parsing/HttpRequestParser.scala
  akka-http-core/src/main/scala/akka/http/impl/engine/rendering/HttpResponseRendererFactory.scala
  akka-http-core/src/main/scala/akka/http/impl/engine/server/HttpServerBluePrint.scala
  akka-http-core/src/main/scala/akka/http/impl/engine/server/UpgradeToOtherProtocolResponseHeader.scala
  akka-http-core/src/main/scala/akka/http/impl/engine/ws/Handshake.scala
  akka-http-core/src/main/scala/akka/http/impl/engine/ws/UpgradeToWebSocketLowLevel.scala
  akka-http-core/src/main/scala/akka/http/impl/engine/ws/UpgradeToWebSocketsResponseHeader.scala
  akka-http-core/src/main/scala/akka/http/impl/model/parser/Base64Parsing.scala
  akka-http-core/src/main/scala/akka/http/scaladsl/Http.scala
  akka-http-core/src/test/scala/akka/http/impl/engine/parsing/RequestParserSpec.scala
  akka-http-core/src/test/scala/akka/http/impl/engine/rendering/ResponseRendererSpec.scala
  akka-http-testkit/src/main/scala/akka/http/scaladsl/testkit/WSTestRequestBuilding.scala
  akka-http2-support/src/main/scala/akka/http/impl/engine/http2/FrameEvent.scala
  akka-http2-support/src/main/scala/akka/http/impl/engine/http2/Http2Blueprint.scala
  akka-http2-support/src/main/scala/akka/http/impl/engine/http2/Http2ServerDemux.scala
  akka-http2-support/src/main/scala/akka/http/impl/engine/http2/Http2StreamHandling.scala
  akka-http2-support/src/main/scala/akka/http/impl/engine/http2/framing/Http2FrameParsing.scala
  akka-http2-support/src/main/scala/akka/http/scaladsl/Http2.scala
  akka-http2-support/src/main/scala/akka/http/scaladsl/model/http2/Http2SettingsHeader.scala
  akka-http2-support/src/main/scala/akka/http/scaladsl/model/http2/Http2StreamIdHeader.scala
  akka-http2-support/src/test/scala/akka/http/impl/engine/http2/H2cUpgradeSpec.scala
  akka-http2-support/src/test/scala/akka/http/scaladsl/Http2ServerTest.scala
  docs/src/main/paradox/server-side/http2.md
Labels: 2 - pick next, tested

#2712 Link to StreamPrioritizer javadoc
  docs/src/main/paradox/release-notes/10.0.x.md
Labels: tested

#2713 Avoid hidden-but-invalid links
  docs/src/main/paradox/migration-guide/migration-from-old-http-javadsl.md
  docs/src/main/paradox/server-side/server-https-support.md
Labels: tested

#2715 Fix links to objects
  docs/src/main/paradox/common/http-model.md
  docs/src/main/paradox/routing-dsl/directives/security-directives/authorize.md
Labels: tested

#2701 http2: fix receiving HEADERS with more than one CONTINUATION frame
  akka-http2-support/src/main/scala/akka/http/impl/engine/http2/hpack/HeaderDecompression.scala
  akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2ServerSpec.scala
Labels: 2 - pick next, tested

#2645 Streamed response processing performance improvements
  akka-http-core/src/main/mima-filters/10.1.9.backwards.excludes/response-rendering-performance-improvements.excludes
  akka-http-core/src/main/scala/akka/http/impl/engine/rendering/HttpResponseRendererFactory.scala
  akka-http-core/src/main/scala/akka/http/impl/engine/rendering/RenderSupport.scala
  akka-http-core/src/main/scala/akka/http/impl/engine/server/HttpServerBluePrint.scala
Labels: 2 - pick next, tested

#2717 Add release notes for 10.1.10
  docs/src/main/paradox/release-notes/10.1.x.md
Labels: tested

#2707 build: collapse PR validation report for less clutter
  project/ValidatePullRequest.scala
Labels: tested

#2730 Update scalacheck to 1.14.2
  project/Dependencies.scala
Labels: tested

#2726 Update jackson-dataformat-xml to 2.9.10
  project/Dependencies.scala
Labels: tested

#2714 Update specs2-core to 4.7.1
  project/Dependencies.scala
Labels: tested

#2731 build: use latest Java 1.8 version in Travis
  .travis.yml
Labels: tested
