Repository akka/akka-http, pull requests merged in 2019-08, with the labels that each got.

#2624 Widen JavaUUID regexp's
  akka-http-tests/src/test/scala/akka/http/scaladsl/server/directives/PathDirectivesSpec.scala
  akka-http-tests/src/test/scala/akka/http/scaladsl/unmarshalling/UnmarshallingSpec.scala
  akka-http/src/main/scala/akka/http/scaladsl/server/PathMatcher.scala
  akka-http/src/main/scala/akka/http/scaladsl/unmarshalling/PredefinedFromStringUnmarshallers.scala
Labels: tested

#2621 core: pull transformDataBytes(newContentLength, transformer) up to HttpEntity
  akka-http-core/src/main/mima-filters/10.1.9.backwards.excludes/issue-2603-lift-transformDataBytes.excludes
  akka-http-core/src/main/scala/akka/http/scaladsl/model/HttpEntity.scala
Labels: tested

#2627 Better error handling on server when response entity stream fails
  akka-http-core/src/main/scala/akka/http/impl/engine/rendering/HttpResponseRendererFactory.scala
  akka-http-core/src/main/scala/akka/http/impl/engine/server/HttpServerBluePrint.scala
  akka-http-core/src/main/scala/akka/http/impl/util/StreamUtils.scala
  akka-http-core/src/main/scala/akka/http/impl/util/package.scala
  akka-http-core/src/main/scala/akka/http/scaladsl/settings/ServerSettings.scala
  akka-http-core/src/test/scala/akka/http/impl/engine/client/ConnectionPoolSpec.scala
  akka-http-core/src/test/scala/akka/http/impl/engine/server/HttpServerSpec.scala
  akka-http-core/src/test/scala/akka/http/impl/engine/server/HttpServerTestSetupBase.scala
Labels: tested

#2638 Release train updates
  notes/release-train-issue-template.md
Labels: tested

#2636 Silence AbruptTerminationExceptions during shutdown in tests
  akka-http-core/src/test/scala/akka/http/impl/engine/client/ConnectionPoolSpec.scala
  akka-http-core/src/test/scala/akka/http/impl/engine/client/HostConnectionPoolSpec.scala
  akka-http-core/src/test/scala/akka/http/impl/engine/ws/FramingSpec.scala
  akka-http-core/src/test/scala/akka/http/impl/engine/ws/MessageSpec.scala
  akka-http-core/src/test/scala/akka/http/impl/engine/ws/Utf8CodingSpecs.scala
  akka-http-core/src/test/scala/akka/http/impl/engine/ws/WebSocketClientSpec.scala
  akka-http-core/src/test/scala/akka/http/impl/engine/ws/WebSocketServerSpec.scala
  akka-http-core/src/test/scala/akka/http/impl/engine/ws/WithMaterializerSpec.scala
  akka-http-core/src/test/scala/akka/http/impl/util/AkkaSpecWithMaterializer.scala
  akka-http-core/src/test/scala/akka/http/scaladsl/GracefulTerminationSpec.scala
  akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2ServerSpec.scala
  akka-http2-support/src/test/scala/akka/http/impl/engine/http2/framing/Http2FramingSpec.scala
Labels: tested

#2633 http: reject with MalformedRequestContentRejection if formFieldSeq cannot unmarshal to form
  akka-http-tests/src/test/scala/akka/http/scaladsl/server/directives/FormFieldDirectivesSpec.scala
  akka-http/src/main/scala/akka/http/scaladsl/server/directives/FormFieldDirectives.scala
Labels: tested

#2628 Fix a few warnings
  akka-http-core/src/main/scala/akka/http/impl/engine/client/pool/SlotState.scala
  akka-http-core/src/main/scala/akka/http/scaladsl/model/FormData.scala
Labels: validating

#2635 build: pull sbt-paradox to 0.6.2
  docs/src/main/paradox/client-side/client-transport.md
  docs/src/main/paradox/common/index.md
  docs/src/main/paradox/common/json-support.md
  docs/src/main/paradox/common/sse-support.md
  docs/src/main/paradox/common/xml-support.md
  docs/src/main/paradox/introduction.md
  docs/src/main/paradox/release-notes/10.0.x.md
  docs/src/main/paradox/routing-dsl/directives/coding-directives/decodeRequest.md
  docs/src/main/paradox/routing-dsl/directives/coding-directives/decodeRequestWith.md
  docs/src/main/paradox/routing-dsl/directives/marshalling-directives/completeWith.md
  docs/src/main/paradox/routing-dsl/directives/marshalling-directives/entity.md
  docs/src/main/paradox/routing-dsl/directives/marshalling-directives/handleWith.md
  docs/src/main/paradox/routing-dsl/directives/timeout-directives/index.md
  docs/src/main/paradox/routing-dsl/overview.md
  docs/src/main/paradox/routing-dsl/routes.md
  docs/src/main/paradox/server-side/low-level-api.md
  docs/src/main/paradox/technologies.md
  project/plugins.sbt
Labels: tested

#2641 Fix compilation in 2.11
  akka-http-core/src/test/scala/akka/http/scaladsl/GracefulTerminationSpec.scala
Labels: tested

#2631 Force connection closure when pool is stopped
  akka-http-core/src/main/scala/akka/http/impl/engine/client/pool/NewHostConnectionPool.scala
  akka-http-core/src/main/scala/akka/http/impl/engine/client/pool/SlotState.scala
  akka-http-core/src/test/scala/akka/http/impl/engine/client/HostConnectionPoolSpec.scala
  akka-http-core/src/test/scala/akka/http/impl/engine/client/pool/SlotStateSpec.scala
Labels: tested

#2643 Fix performance regression introduced in #2627
  akka-http-bench-jmh/src/main/scala/akka/http/CommonBenchmark.scala
  akka-http-bench-jmh/src/main/scala/akka/http/impl/engine/HeaderParserBenchmark.scala
  akka-http-bench-jmh/src/main/scala/akka/http/impl/engine/ServerProcessingBenchmark.scala
  akka-http-core/src/main/scala/akka/http/impl/engine/server/HttpServerBluePrint.scala
Labels: tested

#2647 core: enable log-unencrypted-network-bytes also for websocket client traffic
  akka-http-core/src/main/scala/akka/http/impl/engine/ws/WebSocketClientBlueprint.scala
Labels: tested

#2644 Add benchmark to compare strict vs streamed response types
  akka-http-bench-jmh/src/main/scala/akka/http/impl/engine/ServerProcessingBenchmark2.scala
  akka-http-core/src/main/scala/akka/http/impl/engine/server/HttpServerBluePrint.scala
Labels: tested

#2630 Rewrite pool interface without actors
  akka-http-core/src/main/mima-filters/10.1.9.backwards.excludes/issue-2617-PoolInterfaceActor-rewrite.excludes
  akka-http-core/src/main/scala/akka/http/impl/engine/client/PoolInterface.scala
  akka-http-core/src/main/scala/akka/http/impl/engine/client/PoolInterfaceActor.scala
  akka-http-core/src/main/scala/akka/http/impl/engine/client/PoolMasterActor.scala
  akka-http-core/src/main/scala/akka/http/impl/engine/client/pool/NewHostConnectionPool.scala
  akka-http-core/src/main/scala/akka/http/impl/util/StreamUtils.scala
  akka-http-core/src/test/scala/akka/http/impl/engine/client/ConnectionPoolSpec.scala
  akka-http-core/src/test/scala/akka/http/impl/engine/client/HostConnectionPoolSpec.scala
Labels: tested

#2657 Update paradox
  project/plugins.sbt
Labels: tested

#2660 Fix javadsl test compilation against akka master
  akka-http-core/src/test/scala/akka/http/javadsl/HttpExtensionApiSpec.scala
  akka-http-core/src/test/scala/akka/http/scaladsl/GracefulTerminationSpec.scala
Labels: tested

#2656 Update mima
  akka-http-caching/src/main/mima-filters/10.1.8.backwards.excludes
  akka-http-core/src/main/mima-filters/10.0.11.backwards.excludes
  akka-http-core/src/main/mima-filters/10.1.8.backwards.excludes
  akka-http/src/main/mima-filters/10.0.11.backwards.excludes
  project/plugins.sbt
Labels: tested

#2661 Reduce scope of mima filters
  akka-http-caching/src/main/mima-filters/10.1.5.backwards.excludes
  akka-http-caching/src/main/mima-filters/10.1.8.backwards.excludes
  akka-http-core/src/main/mima-filters/10.0.15.backwards.excludes
  akka-http-core/src/main/mima-filters/10.0.9.backwards.excludes
  akka-http-core/src/main/mima-filters/10.1.0.backwards.excludes
  akka-http-core/src/main/mima-filters/10.1.1.backwards.excludes
  akka-http-core/src/main/mima-filters/10.1.3.backwards.excludes
  akka-http-core/src/main/mima-filters/10.1.5.backwards.excludes
  akka-http-core/src/main/mima-filters/10.1.7.backwards.excludes
  akka-http-core/src/main/mima-filters/10.1.8.backwards.excludes
  akka-http/src/main/mima-filters/10.1.1.backwards.excludes
  akka-http/src/main/mima-filters/10.1.5.backwards.excludes
  akka-http/src/main/mima-filters/10.1.8.backwards.excludes
Labels: tested

#2655 Update Scala to 2.12.9
  project/Dependencies.scala
Labels: tested

#2650 [WIP] Akka typed examples
  build.sbt
  docs/src/main/paradox/client-side/host-level.md
  docs/src/main/paradox/routing-dsl/HttpApp.md
  docs/src/main/paradox/routing-dsl/directives/basic-directives/extractActorSystem.md
  docs/src/main/paradox/routing-dsl/index.md
  docs/src/test/scala/docs/http/scaladsl/HttpServerWithTypedSpec.scala
Labels: tested

#2662 Scaladoc: link to source and canonical
  project/Doc.scala
Labels: t:docs, tested

#2654 build: add command line flag that allows running akka-http-core tests against akka master branch
  build.sbt
  project/AkkaDependency.scala
Labels: tested

#2665 Fix Routes documentation
  docs/src/main/paradox/routing-dsl/routes.md
Labels: tested

#2653 Reduce number of stages needed to implement CaptureMaterializationAndTerminationOp
  akka-http-core/src/main/scala/akka/http/impl/engine/client/pool/NewHostConnectionPool.scala
  akka-http-core/src/main/scala/akka/http/impl/util/StreamUtils.scala
  akka-http-core/src/test/scala/akka/http/impl/engine/client/HostConnectionPoolSpec.scala
Labels: tested

#2646 Prevent extra error log messages when decoded HttpMessage stream fails
  akka-http-tests/src/test/scala/akka/http/scaladsl/server/directives/CodingDirectivesSpec.scala
  akka-http/src/main/scala/akka/http/scaladsl/coding/Decoder.scala
  akka-http/src/main/scala/akka/http/scaladsl/server/directives/CodingDirectives.scala
Labels: tested

#2667 docs: disable unsupported `-doc-canonical-base-url` for Scala 2.11
  project/Doc.scala
Labels: tested
