Repository akka/akka-http, pull requests merged in 2020-07, with the labels that each got.

#3319 build: update caffeine from 2.8.4 to 2.8.5
  project/Dependencies.scala
Labels: tested

#3320 build: update sbt from 1.3.12 to 1.3.13
  project/build.properties
Labels: tested

#3318 build: update sbt-dynver from 4.0.0 to 4.1.0
  project/plugins.sbt
Labels: tested

#3309 build: update to Scala 2.13.3
  akka-http-core/src/test/scala/akka/http/impl/engine/parsing/HttpHeaderParserSpec.scala
  docs/src/test/scala/docs/http/scaladsl/server/directives/PathDirectivesExamplesSpec.scala
  docs/src/test/scala/docs/http/scaladsl/server/directives/TimeoutDirectivesExamplesSpec.scala
  project/Dependencies.scala
Labels: tested

#3328 Publish docs from travis
  .travis.yml
  project/release.sh
  scripts/release-train-issue-template.md
Labels: tested

#3331 bench: add connection pool benchmark
  akka-http-bench-jmh/src/main/scala/akka/http/impl/engine/ConnectionPoolBenchmark.scala
Labels: tested

#3329 core: make HttpEntity.Strict.discardBytes a no-op
  akka-http-bench-jmh/src/main/scala/akka/http/impl/engine/HttpEntityBenchmark.scala
  akka-http-core/src/main/scala/akka/http/scaladsl/model/HttpEntity.scala
  akka-http-core/src/main/scala/akka/http/scaladsl/model/HttpMessage.scala
Labels: needs-backport, tested

#3314 tests: more reliable waiting for WINDOW_UPDATES
  akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2ServerSpec.scala
Labels: tested

#3312 tests: set a more reasonable PatienceConfig for RoutingSpecs
  akka-http-tests/src/test/scala/akka/http/scaladsl/server/RoutingSpec.scala
Labels: tested

#3307 http: allow 'complete' directive with status without adapted arguments
  akka-http-tests/src/test/scala/akka/http/scaladsl/server/directives/CodingDirectivesSpec.scala
  akka-http-tests/src/test/scala/akka/http/scaladsl/server/directives/ExecutionDirectivesSpec.scala
  akka-http-tests/src/test/scala/akka/http/scaladsl/server/directives/FutureDirectivesSpec.scala
  akka-http-tests/src/test/scala/akka/http/scaladsl/server/directives/RouteDirectivesSpec.scala
  akka-http/src/main/scala/akka/http/scaladsl/server/ExceptionHandler.scala
  akka-http/src/main/scala/akka/http/scaladsl/server/directives/RangeDirectives.scala
  akka-http/src/main/scala/akka/http/scaladsl/server/directives/RouteDirectives.scala
  docs/src/main/paradox/migration-guide/migration-from-spray.md
  docs/src/test/scala/docs/http/scaladsl/HttpServerWithActorInteraction.scala
  docs/src/test/scala/docs/http/scaladsl/server/RejectionHandlerExamplesSpec.scala
  docs/src/test/scala/docs/http/scaladsl/server/directives/ExecutionDirectivesExamplesSpec.scala
  docs/src/test/scala/docs/http/scaladsl/server/directives/FutureDirectivesExamplesSpec.scala
Labels: tested

#3334 build: pull up sbt-assembly dependency to stay compatible with akka master
  project/plugins.sbt
Labels: tested

#3338 docs: page about client-side configuration + per-host-overrides
  akka-http-core/src/main/resources/reference.conf
  docs/src/main/paradox/client-side/configuration.md
  docs/src/main/paradox/client-side/index.md
  docs/src/main/paradox/release-notes/10.2.x.md
Labels: tested

#3336 build: show scala version at starting up sbt (or selecting another cross version)
  build.sbt
Labels: tested

#3337 Fix remaining internal adapted arguments warnings
  akka-http/src/main/scala/akka/http/scaladsl/server/ExceptionHandler.scala
  akka-http/src/main/scala/akka/http/scaladsl/server/directives/RangeDirectives.scala
Labels: tested

#3343 build: cleanup in docs config
  CONTRIBUTING.md
  build.sbt
  project/Doc.scala
  project/Github.scala
Labels: tested

#3345 docs: disallow auto-tupling
  build.sbt
  docs/src/test/scala/docs/http/scaladsl/server/directives/FutureDirectivesExamplesSpec.scala
Labels: tested

#3321 core: disable server-side HTTP pipelining by default
  akka-http-core/src/main/resources/reference.conf
  akka-http-core/src/test/scala/akka/http/impl/engine/server/HttpServerSpec.scala
  akka-http-core/src/test/scala/akka/http/impl/engine/server/HttpServerTestSetupBase.scala
  docs/src/main/paradox/migration-guide/migration-guide-10.2.x.md
Labels: tested

#3344 Fix compiler warnings
  akka-http-caching/src/main/scala/akka/http/caching/scaladsl/Cache.scala
  akka-http-core/src/main/scala/akka/http/impl/engine/client/PoolMasterActor.scala
  akka-http-core/src/main/scala/akka/http/impl/engine/parsing/HttpMessageParser.scala
  akka-http-core/src/main/scala/akka/http/impl/engine/parsing/HttpResponseParser.scala
  akka-http-core/src/main/scala/akka/http/impl/util/Rendering.scala
  akka-http-core/src/main/scala/akka/http/impl/util/package.scala
  akka-http-core/src/main/scala/akka/http/scaladsl/Http.scala
  akka-http-core/src/main/scala/akka/http/scaladsl/model/ws/Message.scala
  akka-http-core/src/test/scala/akka/http/impl/engine/client/ConnectionPoolSpec.scala
  akka-http-core/src/test/scala/akka/http/impl/engine/client/HttpsProxyGraphStageSpec.scala
  akka-http-core/src/test/scala/akka/http/impl/engine/client/LowLevelOutgoingConnectionSpec.scala
  akka-http-core/src/test/scala/akka/http/impl/engine/client/PrepareResponseSpec.scala
  akka-http-core/src/test/scala/akka/http/impl/engine/client/ResponseParsingMergeSpec.scala
  akka-http-core/src/test/scala/akka/http/impl/engine/client/pool/SlotStateSpec.scala
  akka-http-core/src/test/scala/akka/http/impl/engine/parsing/HttpHeaderParserSpec.scala
  akka-http-core/src/test/scala/akka/http/impl/engine/server/HttpServerSpec.scala
  akka-http-core/src/test/scala/akka/http/impl/engine/server/HttpServerTestSetupBase.scala
  akka-http-core/src/test/scala/akka/http/impl/engine/ws/MessageSpec.scala
  akka-http-core/src/test/scala/akka/http/impl/engine/ws/WebSocketIntegrationSpec.scala
  akka-http-core/src/test/scala/akka/http/scaladsl/ClientServerSpec.scala
  akka-http-core/src/test/scala/akka/http/scaladsl/GracefulTerminationSpec.scala
  akka-http-core/src/test/scala/akka/http/scaladsl/model/HttpEntitySpec.scala
  akka-http-core/src/test/scala/akka/http/scaladsl/model/headers/HeaderSpec.scala
  akka-http-core/src/test/scala/akka/http/scaladsl/util/FastFutureSpec.scala
  akka-http-core/src/test/scala/akka/testkit/Coroner.scala
  akka-http-tests/src/multi-jvm/scala/akka/remote/testkit/MultiNodeConfig.scala
  akka-http-tests/src/test/scala/akka/http/scaladsl/marshalling/MarshallingSpec.scala
  akka-http-tests/src/test/scala/akka/http/scaladsl/server/directives/DebuggingDirectivesSpec.scala
  akka-http-tests/src/test/scala/akka/http/scaladsl/server/directives/TimeoutDirectivesSpec.scala
  akka-http/src/main/scala/akka/http/javadsl/server/RejectionHandler.scala
  akka-http/src/main/scala/akka/http/javadsl/server/directives/RouteDirectives.scala
  akka-http/src/main/scala/akka/http/scaladsl/coding/Encoder.scala
  akka-http/src/main/scala/akka/http/scaladsl/server/RequestContextImpl.scala
  akka-http2-support/src/main/scala/akka/http/impl/engine/http2/framing/FrameRenderer.scala
  akka-http2-support/src/main/scala/akka/http/scaladsl/Http2.scala
  akka-http2-support/src/test/scala/akka/http/impl/engine/http2/ProtocolSwitchSpec.scala
  akka-http2-support/src/test/scala/akka/http/impl/engine/http2/package.scala
  akka-http2-support/src/test/scala/akka/http/scaladsl/Http2BindingViaConfigSpec.scala
  akka-http2-support/src/test/scala/akka/http/scaladsl/Http2ServerTest.scala
Labels: tested

#3348 Fix some more warnings
  akka-http/src/main/boilerplate/akka/http/javadsl/server/JavaPathMatchers.scala.template
  akka-http/src/main/scala/akka/http/javadsl/marshalling/Marshaller.scala
  akka-http/src/main/scala/akka/http/scaladsl/server/PathMatcher.scala
  akka-http/src/main/scala/akka/http/scaladsl/server/directives/FormFieldDirectives.scala
  akka-parsing/src/main/scala/akka/parboiled2/Rule.scala
  akka-parsing/src/main/scala/akka/parboiled2/support/OpTreeContext.scala
Labels: tested

#3350 build: fail on JavaConverter warnings in docs
  build.sbt
Labels: tested

#3352 core: make sure to reset all UriParser fields before reusing
  akka-http-core/src/main/scala/akka/http/impl/engine/parsing/HttpRequestParser.scala
  akka-http-core/src/main/scala/akka/http/impl/model/parser/UriParser.scala
  akka-http-core/src/test/scala/akka/http/scaladsl/ClientServerSpec.scala
Labels: tested

#3354 docs: use Route directly in exception handler
  docs/src/test/scala/docs/http/scaladsl/server/directives/FutureDirectivesExamplesSpec.scala
Labels: tested

#3353 build: update sbt-paradox-akka from 0.33 to 0.34
  docs/src/main/paradox/migration-guide/migration-from-old-http-javadsl.md
  docs/src/main/paradox/migration-guide/migration-guide-10.2.x.md
  docs/src/main/paradox/routing-dsl/directives/alphabetically.md
  docs/src/main/paradox/routing-dsl/directives/file-and-resource-directives/index.md
  docs/src/main/paradox/routing-dsl/directives/future-directives/onComplete.md
  docs/src/main/paradox/routing-dsl/directives/index.md
  docs/src/main/paradox/routing-dsl/directives/misc-directives/extractClientIP.md
  docs/src/main/paradox/routing-dsl/directives/route-directives/complete.md
  docs/src/main/paradox/routing-dsl/directives/route-directives/handle.md
  docs/src/main/paradox/routing-dsl/directives/route-directives/index.md
  docs/src/main/paradox/routing-dsl/directives/route-directives/reject.md
  docs/src/main/paradox/routing-dsl/directives/security-directives/authorizeAsync.md
  docs/src/main/paradox/routing-dsl/exception-handling.md
  docs/src/main/paradox/routing-dsl/overview.md
  docs/src/main/paradox/routing-dsl/rejections.md
  docs/src/main/paradox/routing-dsl/routes.md
  project/plugins.sbt
Labels: tested

#3347 core: keep request/response copy method public
  akka-http-core/src/main/scala/akka/http/scaladsl/model/HttpMessage.scala
Labels: tested

#3361 Accept classic provider in more places
  akka-http-core/src/main/java/akka/http/javadsl/model/HttpEntity.java
  akka-http-core/src/main/java/akka/http/javadsl/model/HttpMessage.java
  akka-http-core/src/main/mima-filters/10.1.x.backwards.excludes/3361-more-ClassicActorSystemProvider-discard.excludes
  akka-http-core/src/main/mima-filters/10.1.x.backwards.excludes/3361-more-ClassicActorSystemProvider-toStrict.excludes
  akka-http-core/src/main/scala/akka/http/javadsl/Http.scala
  akka-http-core/src/main/scala/akka/http/scaladsl/model/HttpEntity.scala
  akka-http-core/src/main/scala/akka/http/scaladsl/model/HttpMessage.scala
  akka-http-core/src/test/java/akka/http/javadsl/model/EntityDiscardingTest.java
  akka-http-marshallers-java/akka-http-jackson/src/test/java/akka/http/javadsl/marshallers/jackson/JacksonTest.java
  akka-http-tests/src/test/java/akka/http/javadsl/server/UnmarshallerTest.java
  akka-http-tests/src/test/java/akka/http/javadsl/unmarshalling/sse/EventStreamUnmarshallingTest.java
  akka-http/src/main/scala/akka/http/javadsl/unmarshalling/Unmarshaller.scala
  docs/src/test/java/docs/http/javadsl/ClientSingleRequestExample.java
  docs/src/test/java/docs/http/javadsl/CustomMediaTypesExampleTest.java
  docs/src/test/java/docs/http/javadsl/HttpClientDecodingExampleTest.java
  docs/src/test/java/docs/http/javadsl/HttpClientExampleDocTest.java
  docs/src/test/java/docs/http/javadsl/HttpServerLowLevelExample.java
  docs/src/test/java/docs/http/javadsl/JacksonXmlExampleTest.java
  docs/src/test/java/docs/http/javadsl/UnmarshalTest.java
  docs/src/test/java/docs/http/javadsl/server/HttpServerExampleDocTest.java
  docs/src/test/java/docs/http/javadsl/server/JsonStreamingExamplesTest.java
  docs/src/test/java/docs/http/javadsl/server/directives/CustomHttpMethodExamplesTest.java
Labels: tested

#3357 Track idle slots explicitly to avoid O(n^2) work for big pools
  akka-http-bench-jmh/src/main/scala/akka/http/impl/engine/ConnectionPoolBenchmark.scala
  akka-http-core/src/main/scala/akka/http/impl/engine/client/pool/NewHostConnectionPool.scala
Labels: tested

#3355 Add directives for extracting attributes
  akka-http-tests/src/test/java/akka/http/javadsl/server/directives/AttributeDirectivesTest.java
  akka-http-tests/src/test/scala/akka/http/scaladsl/server/directives/AttributeDirectivesSpec.scala
  akka-http/src/main/scala/akka/http/javadsl/server/Rejections.scala
  akka-http/src/main/scala/akka/http/javadsl/server/directives/AttributeDirectives.scala
  akka-http/src/main/scala/akka/http/javadsl/server/directives/HostDirectives.scala
  akka-http/src/main/scala/akka/http/scaladsl/client/RequestBuilding.scala
  akka-http/src/main/scala/akka/http/scaladsl/server/Directives.scala
  akka-http/src/main/scala/akka/http/scaladsl/server/Rejection.scala
  akka-http/src/main/scala/akka/http/scaladsl/server/RejectionHandler.scala
  akka-http/src/main/scala/akka/http/scaladsl/server/directives/AttributeDirectives.scala
  docs/src/main/paradox/routing-dsl/directives/alphabetically.md
  docs/src/main/paradox/routing-dsl/directives/attribute-directives/attribute.md
  docs/src/main/paradox/routing-dsl/directives/attribute-directives/index.md
  docs/src/main/paradox/routing-dsl/directives/attribute-directives/optionalAttribute.md
  docs/src/main/paradox/routing-dsl/directives/by-trait.md
  docs/src/test/java/docs/http/javadsl/server/directives/AttributeDirectivesExamplesTest.java
  docs/src/test/scala/docs/http/scaladsl/server/directives/AttributeDirectivesExamplesSpec.scala
Labels: tested

#3366 core: cleanup HttpMessage.copy chaos introduced in #3347
  akka-http-core/src/main/scala/akka/http/scaladsl/model/HttpMessage.scala
Labels: tested

#3360 tests: enable more logging in Http2ClientServerSpec
  akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2ClientServerSpec.scala
  akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2FrameProbe.scala
  akka-http2-support/src/test/scala/akka/http/scaladsl/Http2BindingViaConfigSpec.scala
Labels: tested

#3369 Http2 benchmarks
  akka-http-bench-jmh/src/main/scala/akka/http/impl/engine/http2/H2ServerProcessingBenchmark.scala
  akka-http2-support/src/main/scala/akka/http/impl/engine/http2/ResponseRendering.scala
  akka-http2-support/src/main/scala/akka/http/scaladsl/Http2.scala
  build.sbt
Labels: tested

#3370 tests: avoid temporaryHostNameAndPort in several tests
  akka-http-core/src/test/scala/akka/http/impl/engine/client/HighLevelOutgoingConnectionSpec.scala
  akka-http-tests/src/test/scala/akka/http/scaladsl/CustomStatusCodesSpec.scala
  docs/src/test/scala/docs/http/scaladsl/server/directives/TimeoutDirectivesExamplesSpec.scala
Labels: tested

#3202 core: introduce custom hostname resolution client transport
  akka-http-core/src/main/scala/akka/http/javadsl/ClientTransport.scala
  akka-http-core/src/main/scala/akka/http/scaladsl/ClientTransport.scala
  akka-http-core/src/test/scala/akka/http/scaladsl/ClientTransportWithCustomResolverSpec.scala
  docs/src/main/paradox/client-side/client-transport.md
  docs/src/main/paradox/release-notes/10.2.x.md
  docs/src/main/paradox/technologies.md
Labels: tested

#3367 http: add handlePF directive
  akka-http-tests/src/test/scala/akka/http/scaladsl/server/directives/RouteDirectivesSpec.scala
  akka-http/src/main/scala/akka/http/javadsl/server/directives/RouteDirectives.scala
  akka-http/src/main/scala/akka/http/scaladsl/server/directives/RouteDirectives.scala
  docs/src/main/paradox/routing-dsl/directives/route-directives/handle.md
  docs/src/main/paradox/routing-dsl/directives/route-directives/handleSync.md
  docs/src/main/paradox/routing-dsl/directives/route-directives/index.md
  docs/src/test/scala/docs/http/scaladsl/server/directives/RouteDirectivesExamplesSpec.scala
Labels: tested

#3330 bench: rename ServerProcessingBenchmark2 and reduce number of configurations
  akka-http-bench-jmh/src/main/scala/akka/http/impl/engine/StreamServerProcessingBenchmark.scala
Labels: tested

#3351 core: make HttpRequest/HttpResponse.hashCode depend on attributes
  akka-http-core/src/main/scala/akka/http/scaladsl/model/HttpMessage.scala
  akka-http-core/src/test/scala/akka/http/scaladsl/model/HttpMessageSpec.scala
Labels: 2 - pick next, tested

#3380 build: update jackson-databind from 2.10.4 to 2.10.5
  project/Dependencies.scala
Labels: tested

#3381 build: update github-api from 1.114 to 1.115
  project/plugins.sbt
Labels: tested

#3382 core: polishing and docs for ServerBuilder API
  akka-http-core/src/main/resources/reference.conf
  akka-http-core/src/main/scala/akka/http/javadsl/Http.scala
  akka-http-core/src/main/scala/akka/http/javadsl/ServerBuilder.scala
  akka-http-core/src/main/scala/akka/http/scaladsl/Http.scala
  akka-http-core/src/main/scala/akka/http/scaladsl/ServerBuilder.scala
  akka-http-core/src/test/scala/akka/http/impl/engine/client/HostConnectionPoolSpec.scala
  akka-http-core/src/test/scala/akka/http/scaladsl/ClientServerSpec.scala
  akka-http-testkit/src/main/scala/akka/http/scaladsl/testkit/RouteTest.scala
  akka-http-tests/src/multi-jvm/scala/akka/http/AkkaHttpServerLatencyMultiNodeSpec.scala
  akka-http-tests/src/test/java/akka/http/javadsl/HttpAPIsTest.java
  akka-http/src/main/scala/akka/http/scaladsl/server/HttpApp.scala
  docs/src/main/paradox/migration-guide/migration-from-spray.md
  docs/src/main/paradox/migration-guide/migration-guide-10.2.x.md
  docs/src/main/paradox/release-notes/10.2.x.md
  docs/src/main/paradox/server-side/http2.md
  docs/src/test/java/docs/http/javadsl/server/AkkaHttp1020MigrationExample.java
  docs/src/test/scala/docs/http/scaladsl/HttpServerExampleSpec.scala
  docs/src/test/scala/docs/http/scaladsl/HttpServerHighLevel.scala
  docs/src/test/scala/docs/http/scaladsl/server/AkkaHttp1020MigrationSpec.scala
  docs/src/test/scala/docs/http/scaladsl/server/HttpsServerExampleSpec.scala
Labels: tested

#3383 core: reverse call propagation for deprecated bind vs. bindImpl methods
  akka-http-core/src/main/scala/akka/http/scaladsl/Http.scala
Labels: tested

#3384 docs: add 'troubleshooting' page, populate with 'PRI' error message
  docs/src/main/paradox/tipsandtricks.md
  docs/src/main/paradox/troubleshooting/index.md
  docs/src/main/paradox/troubleshooting/unsupported-http-method-pri.md
Labels: tested

#3386 Convert more javadsl doc examples from bindAndHandle to ServerBuilder
  akka-http-core/src/main/scala/akka/http/javadsl/ServerBuilder.scala
  akka-http-core/src/test/scala/akka/http/javadsl/HttpExtensionApiSpec.scala
  akka-http-core/src/test/scala/akka/http/scaladsl/ClientServerSpec.scala
  akka-http-tests/src/main/java/akka/http/javadsl/server/examples/petstore/PetStoreExample.java
  akka-http-tests/src/main/java/akka/http/javadsl/server/examples/simple/SimpleServerApp.java
  akka-http-tests/src/main/java/akka/http/javadsl/server/examples/simple/SimpleServerHttpHttpsApp.java
  akka-http/src/main/java/akka/http/javadsl/server/HttpApp.java
  akka-http2-support/src/main/scala/akka/http/impl/engine/http2/Http2Blueprint.scala
  akka-http2-support/src/test/scala/akka/http/scaladsl/Http2BindingViaConfigSpec.scala
  docs/src/main/paradox/routing-dsl/testkit.md
  docs/src/test/java/docs/http/javadsl/ComposeDirectivesExampleTest.java
  docs/src/test/java/docs/http/javadsl/CustomStatusCodesExampleTest.java
  docs/src/test/java/docs/http/javadsl/ExceptionHandlerExample.java
  docs/src/test/java/docs/http/javadsl/RespondWithHeaderHandlerExampleTest.java
  docs/src/test/java/docs/http/javadsl/RouteSealExample.java
  docs/src/test/java/docs/http/javadsl/server/HighLevelServerBindFailureExample.java
  docs/src/test/java/docs/http/javadsl/server/HighLevelServerExample.java
  docs/src/test/java/docs/http/javadsl/server/ServerShutdownExampleTest.java
  docs/src/test/java/docs/http/javadsl/server/directives/TimeoutDirectivesExamplesTest.java
  docs/src/test/java/docs/http/javadsl/server/testkit/MyAppService.java
Labels: tested

#2983 core: allow creating HttpsConnectionContext from SSLContext/Engine
  akka-http-core/src/main/mima-filters/10.1.12.backwards.excludes/2983-sslcontext.backwards.excludes
  akka-http-core/src/main/scala/akka/http/javadsl/ConnectionContext.scala
  akka-http-core/src/main/scala/akka/http/javadsl/Http.scala
  akka-http-core/src/main/scala/akka/http/scaladsl/ConnectionContext.scala
  akka-http-core/src/main/scala/akka/http/scaladsl/Http.scala
  akka-http-core/src/test/scala/akka/http/impl/engine/client/TlsEndpointVerificationSpec.scala
  akka-http-core/src/test/scala/akka/http/impl/util/ExampleHttpContexts.scala
  akka-http-core/src/test/scala/akka/http/scaladsl/ClientServerSpec.scala
  akka-http-core/src/test/scala/akka/http/scaladsl/GracefulTerminationSpec.scala
  akka-http-core/src/test/scala/akka/http/scaladsl/SslConfigWarningsSpec.scala
  akka-http-tests/src/main/java/akka/http/javadsl/server/examples/simple/SimpleServerApp.java
  akka-http-tests/src/main/java/akka/http/javadsl/server/examples/simple/SimpleServerHttpHttpsApp.java
  akka-http2-support/src/main/scala/akka/http/scaladsl/Http2.scala
  docs/src/main/paradox/client-side/client-https-support.md
  docs/src/main/paradox/compatibility-guidelines.md
  docs/src/main/paradox/migration-guide/migration-guide-10.2.x.md
  docs/src/main/paradox/server-side/server-https-support.md
  docs/src/test/scala/docs/http/scaladsl/server/HttpsServerExampleSpec.scala
Labels: tested

#3387 docs: release notes for 10.2.0-RC2
  docs/src/main/paradox/_template/projectSpecificFooter.st
  docs/src/main/paradox/assets/js/scrollToFragment.js
  docs/src/main/paradox/migration-guide/migration-guide-10.2.x.md
  docs/src/main/paradox/release-notes/10.2.x.md
Labels: tested

#3394 core: let's cite all the spec (for WebSocket upgrades)
  akka-http-core/src/main/scala/akka/http/impl/engine/ws/Handshake.scala
Labels: tested

#3396 docs: removed outdated reference to the spray.httpx.marshalling package
  docs/src/main/paradox/routing-dsl/directives/marshalling-directives/completeWith.md
Labels: tested

#3393 build: release train template updates
  scripts/release-train-issue-template.md
Labels: tested

#3401 build: backport AkkaDependency changes from master
  build.sbt
  project/AkkaDependency.scala
Labels: tested
