Repository akka/akka-http, pull requests merged in 2020-06, with the labels that each got.

#3204 [10.1 backport] core: don't fail slot after previous connection failed in special condition
  akka-http-core/src/main/scala/akka/http/impl/engine/client/pool/NewHostConnectionPool.scala
  akka-http-core/src/main/scala/akka/http/impl/engine/client/pool/SlotState.scala
  akka-http-core/src/test/scala/akka/http/impl/engine/client/HostConnectionPoolSpec.scala
Labels: tested

#3207 docs: don't show `route` import in docs
  akka-http-tests/src/test/java/docs/http/javadsl/server/HandlerExampleDocTest.java
  docs/src/test/java/docs/http/javadsl/server/DirectiveExamplesTest.java
  docs/src/test/java/docs/http/javadsl/server/PathDirectiveExampleTest.java
  docs/src/test/java/docs/http/javadsl/server/RejectionHandlerExamplesTest.java
  docs/src/test/java/docs/http/javadsl/server/directives/CustomHttpMethodExamplesTest.java
  docs/src/test/java/docs/http/javadsl/server/directives/MethodDirectivesExamplesTest.java
  docs/src/test/java/docs/http/javadsl/server/directives/PathDirectivesExamplesTest.java
  docs/src/test/java/docs/http/javadsl/server/directives/RouteDirectivesExamplesTest.java
  docs/src/test/java/docs/http/javadsl/server/directives/SchemeDirectivesExamplesTest.java
  docs/src/test/java/docs/http/javadsl/server/directives/WebSocketDirectivesExamplesTest.java
Labels: tested

#3188 core: remove legacy host connection pool including settings and tests
  akka-http-core/src/main/mima-filters/10.1.x.backwards.excludes/3187-remove-legacy-pool.excludes
  akka-http-core/src/main/resources/reference.conf
  akka-http-core/src/main/scala/akka/http/impl/engine/client/PoolConductor.scala
  akka-http-core/src/main/scala/akka/http/impl/engine/client/PoolFlow.scala
  akka-http-core/src/main/scala/akka/http/impl/engine/client/PoolInterface.scala
  akka-http-core/src/main/scala/akka/http/impl/engine/client/PoolSlot.scala
  akka-http-core/src/main/scala/akka/http/impl/settings/ConnectionPoolSettingsImpl.scala
  akka-http-core/src/main/scala/akka/http/impl/util/JavaMapping.scala
  akka-http-core/src/main/scala/akka/http/javadsl/settings/ConnectionPoolSettings.scala
  akka-http-core/src/main/scala/akka/http/scaladsl/settings/ConnectionPoolSettings.scala
  akka-http-core/src/test/scala/akka/http/impl/engine/client/ConnectionPoolSpec.scala
  akka-http-core/src/test/scala/akka/http/impl/engine/client/HostConnectionPoolSpec.scala
  docs/src/main/paradox/migration-guide/migration-guide-10.2.x.md
Labels: tested

#3139 Test: Inspect chunked responses during termination
  akka-http-core/src/test/scala/akka/http/scaladsl/GracefulTerminationSpec.scala
Labels: tested

#2574 core: allow client setting overrides for target hosts in config
  akka-http-core/src/main/mima-filters/10.1.x.backwards.excludes/host-overrides.backwards.excludes
  akka-http-core/src/main/resources/reference.conf
  akka-http-core/src/main/scala/akka/http/impl/settings/ConnectionPoolSettingsImpl.scala
  akka-http-core/src/main/scala/akka/http/javadsl/settings/ConnectionPoolSettings.scala
  akka-http-core/src/main/scala/akka/http/scaladsl/Http.scala
  akka-http-core/src/main/scala/akka/http/scaladsl/settings/ConnectionPoolSettings.scala
  akka-http-core/src/test/scala/akka/http/scaladsl/settings/ConnectionPoolSettingsSpec.scala
  docs/src/main/paradox/compatibility-guidelines.md
Labels: tested

#3210 Clear some warnings
  akka-http-core/src/main/scala-2.13+/akka/http/scaladsl/util/FastFuture.scala
  akka-http-core/src/main/scala/akka/http/impl/engine/client/pool/NewHostConnectionPool.scala
  akka-http-core/src/main/scala/akka/http/impl/util/JavaMapping.scala
  akka-http-core/src/main/scala/akka/http/javadsl/HostConnectionPool.scala
  akka-http-core/src/test/scala/akka/http/impl/engine/parsing/HttpHeaderParserSpec.scala
  akka-http-core/src/test/scala/akka/http/scaladsl/model/headers/HeaderSpec.scala
  build.sbt
  project/Common.scala
Labels: tested

#3176 build: don't silence 'adapted arguments' warning
  project/Common.scala
Labels: tested

#3208 Fail early when creating client settings with incomplete parser settings
  akka-http-core/src/main/scala/akka/http/impl/settings/ClientConnectionSettingsImpl.scala
  akka-http-core/src/main/scala/akka/http/impl/settings/ServerSettingsImpl.scala
  akka-http-core/src/test/scala/akka/http/scaladsl/settings/ClientConnectionSettingsSpec.scala
  akka-http-core/src/test/scala/akka/http/scaladsl/settings/ServerSettingsSpec.scala
Labels: tested

#3215 build: Set build-time jvm locale to en_US.UTF-8
  .jvmopts
  .jvmopts-travis
Labels: tested

#3211 tests: use AkkaSpecWithMaterializer in more places and make it slightly nicer
  akka-http-core/src/test/scala/akka/http/impl/engine/parsing/HttpHeaderParserSpec.scala
  akka-http-core/src/test/scala/akka/http/impl/engine/server/HttpServerBug21008Spec.scala
  akka-http-core/src/test/scala/akka/http/impl/util/AkkaSpecWithMaterializer.scala
  akka-http-core/src/test/scala/akka/http/scaladsl/SslConfigWarningsSpec.scala
  akka-http-core/src/test/scala/akka/http/scaladsl/model/EntityDiscardingSpec.scala
Labels: tested

#3205 tests: Use AkkaSpecWithMaterializer in MultipartUnmarshallerSpec
  akka-http-tests/src/test/scala/akka/http/scaladsl/unmarshalling/MultipartUnmarshallersSpec.scala
Labels: tested

#3206 tests: increase timeout in FileUploadDirectivesSpec once again
  akka-http-tests/src/test/scala/akka/http/scaladsl/server/directives/FileUploadDirectivesSpec.scala
Labels: tested

#3213 tests: proxy transport instead of disabling hostname verification
  akka-http-core/src/test/scala/akka/http/scaladsl/ClientServerSpec.scala
  akka-http-core/src/test/scala/akka/http/scaladsl/GracefulTerminationSpec.scala
Labels: tested

#3218 build: update to Scala 2.13.2 / 2.12.11
  .travis.yml
  akka-http-core/src/test/scala/akka/http/impl/util/AkkaSpecWithMaterializer.scala
  akka-http-testkit/src/main/scala/akka/http/scaladsl/testkit/RouteTestTimeout.scala
  akka-http/src/main/scala/akka/http/scaladsl/marshalling/PredefinedToEntityMarshallers.scala
  project/Dependencies.scala
  project/Doc.scala
Labels: tested

#3217 core: remove internal now-obsolete helper methods
  akka-http-core/src/main/mima-filters/10.1.x.backwards.excludes/remove-internal-Http-impl-methods.excludes
  akka-http-core/src/main/scala/akka/http/javadsl/Http.scala
  akka-http-core/src/main/scala/akka/http/scaladsl/Http.scala
  akka-http-core/src/test/scala/akka/http/impl/engine/client/HostConnectionPoolSpec.scala
  akka-http-core/src/test/scala/akka/http/scaladsl/ClientServerSpec.scala
Labels: tested

#3243 Docs: show Akka HTTP as symbolic version
  build.sbt
  docs/src/main/paradox/common/caching.md
  docs/src/main/paradox/common/json-support.md
  docs/src/main/paradox/common/xml-support.md
  docs/src/main/paradox/compatibility-guidelines.md
  docs/src/main/paradox/introduction.md
  docs/src/main/paradox/routing-dsl/directives/caching-directives/index.md
  docs/src/main/paradox/routing-dsl/testkit.md
  docs/src/main/paradox/server-side/http2.md
  project/AkkaDependency.scala
Labels: t:docs, tested

#3246 [backport #3206] tests: increase timeout in FileUploadDirectivesSpec once again
  akka-http-tests/src/test/scala/akka/http/scaladsl/server/directives/FileUploadDirectivesSpec.scala
Labels: tested

#3238 Allow javadoc generation with jdk11
  project/Doc.scala
Labels: tested

#3223 Update javadsl bindAndHandle to take a Java function and System
  akka-http-core/src/main/scala/akka/http/javadsl/Http.scala
  akka-http-core/src/test/java/akka/http/javadsl/GracefulTerminationCompileTest.java
  akka-http-tests/src/test/java/akka/http/javadsl/HttpAPIsTest.java
  akka-http2-support/src/test/java/akka/http/javadsl/Http2JavaServerTest.java
  docs/src/test/java/docs/http/javadsl/Http2Test.java
  docs/src/test/java/docs/http/javadsl/server/WebSocketCoreExample.java
Labels: tested

#3166 HTTP/2 client implementation stub
  akka-http-core/src/main/mima-filters/10.1.x.backwards.excludes/introduce-http2-client-settings.excludes
  akka-http-core/src/main/resources/reference.conf
  akka-http-core/src/main/scala/akka/http/impl/settings/ClientConnectionSettingsImpl.scala
  akka-http-core/src/main/scala/akka/http/scaladsl/settings/ClientConnectionSettings.scala
  akka-http-core/src/main/scala/akka/http/scaladsl/settings/Http2ServerSettings.scala
  akka-http2-support/src/main/scala/akka/http/impl/engine/http2/Http2Blueprint.scala
  akka-http2-support/src/main/scala/akka/http/impl/engine/http2/Http2Multiplexer.scala
  akka-http2-support/src/main/scala/akka/http/impl/engine/http2/Http2ServerDemux.scala
  akka-http2-support/src/main/scala/akka/http/impl/engine/http2/Http2StreamHandling.scala
  akka-http2-support/src/main/scala/akka/http/impl/engine/http2/IncomingFlowController.scala
  akka-http2-support/src/main/scala/akka/http/impl/engine/http2/RequestParsing.scala
  akka-http2-support/src/main/scala/akka/http/impl/engine/http2/ResponseRendering.scala
  akka-http2-support/src/main/scala/akka/http/impl/engine/http2/client/RequestRendering.scala
  akka-http2-support/src/main/scala/akka/http/impl/engine/http2/client/ResponseParsing.scala
  akka-http2-support/src/main/scala/akka/http/scaladsl/Http2.scala
  akka-http2-support/src/main/scala/akka/http/scaladsl/model/http2/RequestResponseAssociation.scala
  akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2ClientServerSpec.scala
  akka-http2-support/src/test/scala/akka/http/impl/engine/http2/ResponseRenderingSpec.scala
  akka-http2-support/src/test/scala/akka/http/scaladsl/Http2ClientApp.scala
  docs/src/main/paradox/compatibility-guidelines.md
Labels: tested

#3252 build: update silencer-lib, silencer-plugin from 1.6.0 to 1.7.0
  project/Dependencies.scala
Labels: tested

#3253 build: update github-api from 1.111 to 1.114
  project/plugins.sbt
Labels: tested

#3254 build: update sbt from 1.3.10 to 1.3.12
  project/build.properties
Labels: tested

#3256 http2: use reflection for `setApplicationProtocols`
  akka-http2-support/src/main/scala/akka/http/impl/engine/http2/Http2AlpnSupport.scala
  akka-http2-support/src/main/scala/akka/http/scaladsl/Http2.scala
Labels: tested

#3224 Make the http2 stream id an attribute
  akka-http2-support/src/main/scala/akka/http/impl/engine/http2/Http2Blueprint.scala
  akka-http2-support/src/main/scala/akka/http/impl/engine/http2/RequestParsing.scala
  akka-http2-support/src/main/scala/akka/http/impl/engine/http2/ResponseRendering.scala
  akka-http2-support/src/main/scala/akka/http/scaladsl/Http2.scala
  akka-http2-support/src/main/scala/akka/http/scaladsl/model/http2/Http2StreamIdHeader.scala
  akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2ClientServerSpec.scala
  akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2ServerSpec.scala
  akka-http2-support/src/test/scala/akka/http/impl/engine/http2/RequestParsingSpec.scala
Labels: tested

#3257 docs: don't claim that SNI is a security feature
  akka-http-core/src/main/scala/akka/http/scaladsl/Http.scala
  docs/src/main/paradox/client-side/client-https-support.md
  docs/src/test/java/docs/http/javadsl/HttpsExamplesDocTest.java
  docs/src/test/scala/docs/http/scaladsl/HttpsExamplesSpec.scala
Labels: tested

#3237 http: allow 'bindAndHandleAsync' to take a 'Route'
  akka-http/src/main/mima-filters/10.1.x.backwards.excludes/route-to-function.backwards.excludes
  akka-http/src/main/scala/akka/http/javadsl/server/Route.scala
  akka-http/src/main/scala/akka/http/javadsl/server/directives/RouteAdapter.scala
  akka-http/src/main/scala/akka/http/scaladsl/server/RouteResult.scala
  akka-http2-support/src/test/scala/akka/http/h2spec/H2SpecIntegrationSpec.scala
Labels: tested

#3269 tests: speed up Http2ServerSpec by reducing time to check for no messages
  akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2FrameProbe.scala
  akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2ServerSpec.scala
Labels: tested

#3239 http: new `handle` directive to create Route from function
  akka-http-marshallers-scala/akka-http-spray-json/src/test/scala/akka/http/scaladsl/marshallers/sprayjson/SprayJsonSupportSpec.scala
  akka-http-tests/src/test/java/akka/http/javadsl/server/directives/RouteDirectivesTest.java
  akka-http-tests/src/test/scala/akka/http/scaladsl/server/directives/RouteDirectivesSpec.scala
  akka-http/src/main/scala/akka/http/javadsl/server/directives/RouteDirectives.scala
  akka-http/src/main/scala/akka/http/scaladsl/server/directives/RouteDirectives.scala
  docs/src/main/paradox/routing-dsl/directives/route-directives/handle.md
  docs/src/main/paradox/routing-dsl/directives/route-directives/index.md
Labels: tested

#3265 Only show unmarshalling error details when 'verbose-error-messages' is on
  akka-http-core/src/main/scala/akka/http/scaladsl/model/ErrorInfo.scala
  akka-http-marshallers-java/akka-http-jackson/src/main/java/akka/http/javadsl/marshallers/jackson/Jackson.java
  akka-http-marshallers-java/akka-http-jackson/src/test/java/akka/http/javadsl/marshallers/jackson/JacksonTest.java
  akka-http/src/main/scala/akka/http/scaladsl/server/directives/MarshallingDirectives.scala
  build.sbt
  project/Dependencies.scala
Labels: tested

#3192 Deprecations for 10.2.0
  akka-http-core/src/main/java/akka/http/javadsl/model/FormData.java
  akka-http-core/src/main/scala/akka/http/javadsl/settings/ParserSettings.scala
  akka-http-core/src/main/scala/akka/http/javadsl/settings/ServerSettings.scala
  akka-http-core/src/main/scala/akka/http/scaladsl/settings/ServerSettings.scala
Labels: tested

#3267 Fix warning in Http2 server side
  akka-http-core/src/test/scala/akka/http/impl/util/WithLogCapturing.scala
  akka-http2-support/src/main/scala/akka/http/impl/engine/http2/FrameLogger.scala
  akka-http2-support/src/main/scala/akka/http/impl/engine/http2/Http2Multiplexer.scala
  akka-http2-support/src/main/scala/akka/http/impl/engine/http2/Http2ServerDemux.scala
  akka-http2-support/src/main/scala/akka/http/impl/engine/http2/Http2StreamHandling.scala
  akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2ServerSpec.scala
Labels: tested

#3261 core: fix some warnings
  akka-http-core/src/main/scala/akka/http/impl/engine/parsing/BodyPartParser.scala
  akka-http-core/src/main/scala/akka/http/impl/util/package.scala
  akka-http-core/src/main/scala/akka/http/scaladsl/model/Uri.scala
  akka-http-core/src/test/scala/akka/http/impl/engine/client/ConnectionPoolSpec.scala
  akka-http-core/src/test/scala/akka/http/impl/engine/parsing/HttpHeaderParserSpec.scala
  akka-http-core/src/test/scala/akka/http/impl/engine/parsing/RequestParserSpec.scala
  akka-http-core/src/test/scala/akka/http/impl/engine/server/HttpServerSpec.scala
  akka-http-core/src/test/scala/akka/http/impl/util/BenchUtils.scala
  akka-http-core/src/test/scala/akka/http/scaladsl/ClientServerSpec.scala
  akka-http-core/src/test/scala/akka/http/scaladsl/settings/SettingsEqualitySpec.scala
Labels: tested

#3262 Deprecate internal parts of coding infrastructure
  akka-http/src/main/java/akka/http/javadsl/coding/Coder.java
  akka-http/src/main/scala/akka/http/scaladsl/coding/Decoder.scala
  akka-http/src/main/scala/akka/http/scaladsl/coding/Deflate.scala
  akka-http/src/main/scala/akka/http/scaladsl/coding/DeflateCompressor.scala
  akka-http/src/main/scala/akka/http/scaladsl/coding/Encoder.scala
  akka-http/src/main/scala/akka/http/scaladsl/coding/Gzip.scala
  akka-http/src/main/scala/akka/http/scaladsl/coding/GzipCompressor.scala
  akka-http/src/main/scala/akka/http/scaladsl/coding/NoCoding.scala
  docs/src/test/scala/docs/http/scaladsl/server/directives/CodingDirectivesExamplesSpec.scala
Labels: needs-backport, tested

#3275 tests: don't use `view.mapValues` as it breaks 2.12 compilation
  akka-http-core/src/test/scala/akka/http/impl/util/WithLogCapturing.scala
Labels: tested

#3272 build: update sbt-reproducible-builds from 0.24 to 0.25
  project/plugins.sbt
Labels: tested

#3258 [10.1 backport] server-side streamCancellationDelay
  akka-http-core/src/main/mima-filters/10.1.12.backwards.excludes/3022-fix-server-side-cancellation-races.excludes
  akka-http-core/src/main/resources/reference.conf
  akka-http-core/src/main/scala/akka/http/impl/engine/server/HttpServerBluePrint.scala
  akka-http-core/src/main/scala/akka/http/impl/settings/ServerSettingsImpl.scala
  akka-http-core/src/main/scala/akka/http/impl/util/StreamUtils.scala
  akka-http-core/src/main/scala/akka/http/javadsl/settings/ServerSettings.scala
  akka-http-core/src/main/scala/akka/http/scaladsl/Http.scala
  akka-http-core/src/main/scala/akka/http/scaladsl/settings/ServerSettings.scala
  akka-http-core/src/test/scala/akka/http/impl/engine/server/HttpServerSpec.scala
  akka-http-core/src/test/scala/akka/http/impl/engine/server/HttpServerWithExplicitSchedulerSpec.scala
  akka-http-core/src/test/scala/akka/http/scaladsl/ClientServerSpec.scala
Labels: tested

#3274 build: update specs2-core from 4.9.4 to 4.10.0
  project/Dependencies.scala
Labels: tested

#3277 build: stay on ScalaTest 3.1.x
  .scala-steward.conf
Labels: tested

#3157 Simplify pool access
  akka-http-compatibility-tests/src/main/scala/example/HostConnectionPoolCompat.scala
  akka-http-compatibility-tests/src/test/scala/akka/http/scaladsl/HostConnectionPoolCompatSpec.scala
  akka-http-core/src/main/mima-filters/10.1.x.backwards.excludes/internal-pool-api-refactoring.excludes
  akka-http-core/src/main/scala/akka/http/impl/engine/client/PoolGateway.scala
  akka-http-core/src/main/scala/akka/http/impl/engine/client/PoolId.scala
  akka-http-core/src/main/scala/akka/http/impl/engine/client/PoolInterface.scala
  akka-http-core/src/main/scala/akka/http/impl/engine/client/PoolMasterActor.scala
  akka-http-core/src/main/scala/akka/http/scaladsl/Http.scala
  akka-http-core/src/test/scala/akka/http/impl/engine/client/ConnectionPoolSpec.scala
Labels: tested

#3242 Docs: use new ActorSystem API
  docs/src/main/paradox/introduction.md
  docs/src/test/java/docs/http/javadsl/ClientSingleRequestExample.java
  docs/src/test/java/docs/http/javadsl/HttpServerActorInteractionExample.java
  docs/src/test/java/docs/http/javadsl/HttpServerLowLevelExample.java
  docs/src/test/java/docs/http/javadsl/HttpServerMinimalExampleTest.java
  docs/src/test/java/docs/http/javadsl/HttpServerStreamRandomNumbersTest.java
  docs/src/test/java/docs/http/javadsl/JacksonExampleTest.java
  docs/src/test/scala/docs/http/scaladsl/HttpClientSingleRequest.scala
  docs/src/test/scala/docs/http/scaladsl/HttpServerLowLevel.scala
  docs/src/test/scala/docs/http/scaladsl/HttpServerRoutingMinimal.scala
  docs/src/test/scala/docs/http/scaladsl/HttpServerStreamingRandomNumbers.scala
  docs/src/test/scala/docs/http/scaladsl/HttpServerWithActorInteraction.scala
  docs/src/test/scala/docs/http/scaladsl/SprayJsonExample2.scala
Labels: tested

#3284 docs: exclude testing projects from unidoc
  build.sbt
Labels: t:docs, tested

#3283 Remove 'adapted' println
  akka-http-tests/src/test/scala/akka/http/scaladsl/server/directives/FormFieldDirectivesSpec.scala
Labels: tested

#3282 Remove deprecated 'symbol' notation from tests
  akka-http-tests/src/test/scala/akka/http/scaladsl/server/BasicRouteSpecs.scala
  akka-http-tests/src/test/scala/akka/http/scaladsl/server/TestServer.scala
  akka-http-tests/src/test/scala/akka/http/scaladsl/server/directives/FormFieldDirectivesSpec.scala
  akka-http-tests/src/test/scala/akka/http/scaladsl/server/directives/HeaderDirectivesSpec.scala
  akka-http-tests/src/test/scala/akka/http/scaladsl/server/util/TupleOpsSpec.scala
Labels: tested

#3276 Add test for failure propagation into websocket flows
  akka-http-core/src/test/scala/akka/http/impl/engine/ws/WebSocketIntegrationSpec.scala
Labels: tested

#3279 Allow passing a companion object to headerValueByType
  akka-http-tests/src/test/scala/akka/http/scaladsl/server/ModeledCustomHeaderSpec.scala
  akka-http-tests/src/test/scala/akka/http/scaladsl/server/directives/CacheConditionDirectivesSpec.scala
  akka-http-tests/src/test/scala/akka/http/scaladsl/server/directives/HeaderDirectivesSpec.scala
  akka-http/src/main/scala/akka/http/scaladsl/server/directives/HeaderDirectives.scala
  akka-http/src/main/scala/akka/http/scaladsl/server/directives/SecurityDirectives.scala
  akka-http/src/main/scala/akka/http/scaladsl/server/directives/WebSocketDirectives.scala
  docs/src/main/paradox/migration-guide/migration-guide-10.2.x.md
  docs/src/test/scala/docs/http/scaladsl/server/directives/HeaderDirectivesExamplesSpec.scala
Labels: tested

#3280 Deprecate UpgradeToWebSocket
  akka-http-core/src/main/scala/akka/http/javadsl/model/ws/UpgradeToWebSocket.scala
  docs/src/main/paradox/server-side/websocket-support.md
Labels: tested

#3288 [backport] Add test for failure propagation into websocket flows
  akka-http-core/src/test/scala/akka/http/impl/engine/ws/WebSocketIntegrationSpec.scala
Labels: tested

#3292 http: silence some warnings
  akka-http-tests/src/multi-jvm/scala/akka/http/AkkaHttpServerLatencyMultiNodeSpec.scala
  akka-http/src/main/scala/akka/http/javadsl/server/Directives.scala
Labels: tested

#3289 http: remove magnets usage from formField directives
  akka-http-tests/src/test/scala/akka/http/scaladsl/server/directives/FormFieldDirectivesSpec.scala
  akka-http/src/main/boilerplate/akka/http/scaladsl/server/directives/FormFieldDirectivesInstances.scala.template
  akka-http/src/main/mima-filters/10.1.x.backwards.excludes/formFields-via-FieldSpec.excludes
  akka-http/src/main/scala/akka/http/scaladsl/server/directives/FormFieldDirectives.scala
  docs/src/test/scala/docs/http/scaladsl/HttpServerExampleSpec.scala
Labels: tested

#3162 Deprecate HttpApp
  akka-http-tests/src/test/scala/akka/http/javadsl/server/HttpAppSpec.scala
  akka-http/src/main/java/akka/http/javadsl/server/HttpApp.java
  akka-http/src/main/scala/akka/http/scaladsl/server/HttpApp.scala
  docs/src/main/paradox/release-notes/10.0.x.md
  docs/src/main/paradox/routing-dsl/HttpApp.md
  docs/src/main/paradox/routing-dsl/index.md
  docs/src/test/java/docs/http/javadsl/server/HttpAppExampleTest.java
  docs/src/test/scala/docs/http/scaladsl/HttpAppExampleSpec.scala
Labels: tested

#3294 http: deprecate more of coding infrastructure
  akka-http-tests/src/test/scala/akka/http/scaladsl/coding/CoderSpec.scala
  akka-http-tests/src/test/scala/akka/http/scaladsl/coding/DecoderSpec.scala
  akka-http-tests/src/test/scala/akka/http/scaladsl/coding/DeflateSpec.scala
  akka-http-tests/src/test/scala/akka/http/scaladsl/coding/EncoderSpec.scala
  akka-http-tests/src/test/scala/akka/http/scaladsl/coding/GzipSpec.scala
  akka-http-tests/src/test/scala/akka/http/scaladsl/coding/NoCodingSpec.scala
  akka-http-tests/src/test/scala/akka/http/scaladsl/server/SizeLimitSpec.scala
  akka-http-tests/src/test/scala/akka/http/scaladsl/server/directives/CodingDirectivesSpec.scala
  akka-http-tests/src/test/scala/akka/http/scaladsl/server/directives/ExecutionDirectivesSpec.scala
  akka-http/src/main/scala/akka/http/scaladsl/coding/Coders.scala
  akka-http/src/main/scala/akka/http/scaladsl/coding/Deflate.scala
  akka-http/src/main/scala/akka/http/scaladsl/coding/Encoder.scala
  akka-http/src/main/scala/akka/http/scaladsl/coding/Gzip.scala
  akka-http/src/main/scala/akka/http/scaladsl/coding/NoCoding.scala
  akka-http/src/main/scala/akka/http/scaladsl/server/directives/CodingDirectives.scala
  docs/src/main/paradox/migration-guide/migration-guide-10.2.x.md
  docs/src/test/scala/docs/http/scaladsl/HttpClientDecodingExampleSpec.scala
  docs/src/test/scala/docs/http/scaladsl/HttpServerExampleSpec.scala
  docs/src/test/scala/docs/http/scaladsl/server/RejectionHandlerExamplesSpec.scala
  docs/src/test/scala/docs/http/scaladsl/server/directives/CodingDirectivesExamplesSpec.scala
Labels: tested

#3296 Deprecate scaladsl UpgradeToWebSocket
  akka-http-core/src/main/scala/akka/http/scaladsl/model/ws/UpgradeToWebSocket.scala
  docs/src/main/paradox/server-side/websocket-support.md
  docs/src/test/scala/docs/http/scaladsl/server/WebSocketExampleSpec.scala
Labels: tested

#3297 docs: `parameters` and `formFields` in migration guide
  docs/src/main/paradox/migration-guide/migration-guide-10.2.x.md
Labels: tested

#3298 Add RC1 release notes to 10.2.0 release notes page
  docs/src/main/paradox/release-notes/10.2.x.md
Labels: tested

#3301 docs: fix typo in release notes
  docs/src/main/paradox/release-notes/10.2.x.md
Labels: tested

#3303 Some tweaks to the release checklist
  scripts/release-train-issue-template.md
Labels: tested

#3305 build: Use publishRsync plugin
  build.sbt
  project/Publish.scala
  project/plugins.sbt
  scripts/release-train-issue-template.md
Labels: tested
