Repository akka/akka-http, pull requests merged in 2020-04, with the labels that each got.

#2976 Accept RST on an already-half-closed HTTP/2 stream
  akka-http-tests/src/test/scala/akka/http/scaladsl/server/directives/CodingDirectivesSpec.scala
  akka-http-tests/src/test/scala/akka/http/scaladsl/server/directives/FileAndResourceDirectivesSpec.scala
  akka-http-tests/src/test/scala/akka/http/scaladsl/server/directives/MiscDirectivesSpec.scala
  akka-http2-support/src/main/scala/akka/http/impl/engine/http2/Http2StreamHandling.scala
  akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2ServerSpec.scala
  akka-http2-support/src/test/scala/akka/http/scaladsl/Http2ServerTest.scala
  docs/src/test/scala/docs/http/scaladsl/server/directives/FileUploadDirectivesExamplesSpec.scala
Labels: tested

#3034 sbt 1.3.9; Akka Paradox 32
  project/build.properties
  project/plugins.sbt
Labels: t:docs, tested

#3035 [10.1] Akka Paradox 32
  project/plugins.sbt
Labels: t:docs, tested

#3037 Update github-api to 1.109
  project/plugins.sbt
Labels: tested

#3044 build: configure travis git depth to fix sbt-dynver
  .travis.yml
Labels: tested

#3036 Akka 2.5.31; accept ClassicActorSystemProvider in extensions
  akka-http-core/src/main/scala/akka/http/javadsl/Http.scala
  akka-http-core/src/main/scala/akka/http/scaladsl/Http.scala
  akka-http2-support/src/main/scala/akka/http/scaladsl/Http2.scala
  project/AkkaDependency.scala
Labels: tested

#2996 Update docs to Akka 2.6, de-emphasize Materializer
  akka-http-bench-jmh/src/main/scala/akka/http/impl/engine/HeaderParserBenchmark.scala
  akka-http-core/src/main/scala/akka/http/scaladsl/Http.scala
  akka-http-core/src/main/scala/akka/http/scaladsl/settings/ParserSettings.scala
  akka-http-core/src/main/scala/akka/http/scaladsl/settings/SettingsCompanion.scala
  akka-http-core/src/test/java/akka/http/javadsl/model/EntityDiscardingTest.java
  akka-http-core/src/test/scala/akka/http/impl/engine/client/ClientCancellationSpec.scala
  akka-http-core/src/test/scala/akka/http/impl/engine/client/HostConnectionPoolSpec.scala
  akka-http-core/src/test/scala/akka/http/impl/engine/client/ResponseParsingMergeSpec.scala
  akka-http-core/src/test/scala/akka/http/javadsl/HttpExtensionApiSpec.scala
  akka-http-core/src/test/scala/akka/http/javadsl/model/MultipartsSpec.scala
  akka-http-core/src/test/scala/akka/http/scaladsl/ClientServerSpec.scala
  akka-http-core/src/test/scala/akka/http/scaladsl/TestClient.scala
  akka-http-marshallers-scala/akka-http-spray-json/src/test/scala/akka/http/scaladsl/marshallers/sprayjson/SprayJsonSupportSpec.scala
  akka-http-testkit/src/main/scala/akka/http/javadsl/testkit/JUnitRouteTest.scala
  akka-http-testkit/src/main/scala/akka/http/scaladsl/testkit/RouteTest.scala
  akka-http-tests/src/test/scala/akka/http/scaladsl/server/TestServer.scala
  akka-http-tests/src/test/scala/akka/http/scaladsl/unmarshalling/MultipartUnmarshallersSpec.scala
  akka-http-tests/src/test/scala/akka/http/scaladsl/unmarshalling/UnmarshallingSpec.scala
  akka-http/src/main/scala/akka/http/scaladsl/server/Route.scala
  akka-http/src/main/scala/akka/http/scaladsl/server/RouteResult.scala
  akka-http2-support/src/test/scala/akka/http/h2spec/H2SpecIntegrationSpec.scala
  akka-http2-support/src/test/scala/akka/http/scaladsl/Http2ServerTest.scala
  build.sbt
  docs/src/main/paradox/routing-dsl/directives/basic-directives/extractActorSystem.md
  docs/src/main/paradox/routing-dsl/index.md
  docs/src/test/java/docs/http/javadsl/server/directives/RangeDirectivesExamplesTest.java
  docs/src/test/scala/docs/http/scaladsl/Http2Spec.scala
  docs/src/test/scala/docs/http/scaladsl/HttpClientDecodingExampleSpec.scala
  docs/src/test/scala/docs/http/scaladsl/HttpClientExampleSpec.scala
  docs/src/test/scala/docs/http/scaladsl/HttpServerExampleSpec.scala
  docs/src/test/scala/docs/http/scaladsl/HttpServerWithTypedSample.scala
  docs/src/test/scala/docs/http/scaladsl/HttpsExamplesSpec.scala
  docs/src/test/scala/docs/http/scaladsl/SprayJsonExampleSpec.scala
  docs/src/test/scala/docs/http/scaladsl/UnmarshalSpec.scala
  docs/src/test/scala/docs/http/scaladsl/WebSocketClientExampleSpec.scala
  docs/src/test/scala/docs/http/scaladsl/server/ExceptionHandlerExamplesSpec.scala
  docs/src/test/scala/docs/http/scaladsl/server/HttpsServerExampleSpec.scala
  docs/src/test/scala/docs/http/scaladsl/server/RejectionHandlerExamplesSpec.scala
  docs/src/test/scala/docs/http/scaladsl/server/WebSocketExampleSpec.scala
  docs/src/test/scala/docs/http/scaladsl/server/directives/BasicDirectivesExamplesSpec.scala
  docs/src/test/scala/docs/http/scaladsl/server/directives/CustomHttpMethodSpec.scala
  docs/src/test/scala/docs/http/scaladsl/server/directives/JsonStreamingFullExamples.scala
  docs/src/test/scala/docs/http/scaladsl/server/directives/TimeoutDirectivesExamplesSpec.scala
  project/AkkaDependency.scala
Labels: tested

#3047 Update specs2-core to 4.9.3
  project/Dependencies.scala
Labels: tested

#3045 Update github-api to 1.110
  project/plugins.sbt
Labels: tested

#3048 docs: link to major/minor Akka docs
  build.sbt
  docs/src/main/paradox/routing-dsl/routes.md
  project/AkkaDependency.scala
Labels: tested

#3052 Update sbt-header to 5.5.0
  project/plugins.sbt
Labels: tested

#3058 Avoid jgit, replace with git commandline invocation
  project/Whitesource.scala
  project/plugins.sbt
Labels: tested

#3042 core: parse empty query `?` to Query.empty
  akka-http-core/src/main/scala/akka/http/impl/model/parser/UriParser.scala
  akka-http-core/src/test/java/akka/http/javadsl/model/UriTest.java
  akka-http-core/src/test/scala/akka/http/scaladsl/model/UriSpec.scala
Labels: tested

#3061 Fix HeaderParserBenchmark
  akka-http-bench-jmh/src/main/scala/akka/http/impl/engine/HeaderParserBenchmark.scala
Labels: tested

#3059 Update sbt to 1.3.10
  project/build.properties
Labels: tested

#3054 Docs: reduce redirects, prefer https
  akka-http-core/src/main/scala/akka/http/impl/model/parser/SimpleHeaders.scala
  akka-http-core/src/main/scala/akka/http/impl/model/parser/UriParser.scala
  akka-http-core/src/main/scala/akka/http/scaladsl/model/headers/headers.scala
  build.sbt
  docs/src/main/paradox/client-side/client-https-support.md
  docs/src/main/paradox/common/sse-support.md
  docs/src/main/paradox/contributing.md
  docs/src/main/paradox/handling-blocking-operations-in-akka-http-routes.md
  docs/src/main/paradox/migration-guide/migration-from-old-http-javadsl.md
  docs/src/main/paradox/routing-dsl/HttpApp.md
  docs/src/main/paradox/routing-dsl/directives/cache-condition-directives/conditional.md
  docs/src/main/paradox/routing-dsl/directives/form-field-directives/formField.md
  docs/src/main/paradox/routing-dsl/directives/form-field-directives/formFieldMap.md
  docs/src/main/paradox/routing-dsl/directives/form-field-directives/formFieldMultiMap.md
  docs/src/main/paradox/routing-dsl/directives/form-field-directives/formFieldSeq.md
  docs/src/main/paradox/routing-dsl/directives/form-field-directives/formFields.md
  docs/src/main/paradox/routing-dsl/directives/security-directives/authenticateOrRejectWithChallenge.md
  docs/src/main/paradox/routing-dsl/directives/security-directives/index.md
  docs/src/main/paradox/routing-dsl/directives/websocket-directives/handleWebSocketMessagesForOptionalProtocol.md
  docs/src/main/paradox/routing-dsl/exception-handling.md
  docs/src/main/paradox/routing-dsl/overview.md
  docs/src/main/paradox/routing-dsl/source-streaming-support.md
  docs/src/main/paradox/routing-dsl/testkit.md
  docs/src/main/paradox/security/2017-01-23-denial-of-service-via-leak-on-unconsumed-closed-connections.md
  docs/src/main/paradox/server-side/http2.md
  docs/src/main/paradox/server-side/index.md
  docs/src/main/paradox/server-side/low-level-api.md
Labels: tested

#3046 core: make sure to cancel response entity on failure
  akka-http-core/src/main/scala/akka/http/impl/engine/rendering/HttpResponseRendererFactory.scala
  akka-http-core/src/test/scala/akka/http/impl/engine/server/HttpServerSpec.scala
  akka-http-core/src/test/scala/akka/http/impl/engine/ws/ByteStringSinkProbe.scala
  akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2ServerSpec.scala
Labels: needs-backport, tested

#3064 [backport] core: make sure to cancel response entity on failure (#3046)
  akka-http-core/src/main/scala/akka/http/impl/engine/rendering/HttpResponseRendererFactory.scala
  akka-http-core/src/test/scala/akka/http/impl/engine/server/HttpServerSpec.scala
  akka-http-core/src/test/scala/akka/http/impl/engine/ws/ByteStringSinkProbe.scala
  akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2ServerSpec.scala
Labels: tested

#3055 build: test against published snapshots instead of source deps
  build.sbt
  project/AkkaDependency.scala
Labels: tested

#3065 Don't build the docs with Akka 2.5
  project/AkkaDependency.scala
Labels: tested

#3066 Specify a non-snapshot minimum expected Akka version
  project/AkkaDependency.scala
  project/VersionGenerator.scala
Labels: tested

#3051 core: add akka.http.server.remote-address-attribute #2924
  akka-http-core/src/main/java/akka/http/javadsl/model/AttributeKeys.java
  akka-http-core/src/main/mima-filters/10.1.x.backwards.excludes/3051-remote-address-attribute.excludes
  akka-http-core/src/main/resources/reference.conf
  akka-http-core/src/main/scala/akka/http/impl/engine/server/HttpServerBluePrint.scala
  akka-http-core/src/main/scala/akka/http/impl/settings/ServerSettingsImpl.scala
  akka-http-core/src/main/scala/akka/http/javadsl/settings/ServerSettings.scala
  akka-http-core/src/main/scala/akka/http/scaladsl/Http.scala
  akka-http-core/src/main/scala/akka/http/scaladsl/model/AttributeKeys.scala
  akka-http-core/src/main/scala/akka/http/scaladsl/settings/ServerSettings.scala
  akka-http-core/src/test/java/akka/http/javadsl/model/HttpMessageTest.java
  akka-http-core/src/test/scala/akka/http/impl/engine/server/HttpServerSpec.scala
  akka-http/src/main/scala/akka/http/scaladsl/server/directives/MiscDirectives.scala
Labels: tested

#3063 Make `transparent-head-requests` opt-in
  akka-http-core/src/main/resources/reference.conf
  akka-http-core/src/test/scala/akka/http/impl/engine/server/HttpServerSpec.scala
  docs/src/main/paradox/migration-guide/migration-guide-10.2.x.md
Labels: t:server, tested

#3060 Simplify implicits for RouteTest
  akka-http-caching/src/test/scala/akka/http/scaladsl/server/directives/CachingDirectivesSpec.scala
  akka-http-testkit/src/main/scala/akka/http/scaladsl/testkit/RouteTest.scala
  akka-http-testkit/src/test/scala/akka/http/scaladsl/testkit/Specs2RouteTestSpec.scala
  akka-http-tests/src/test/scala/akka/http/scaladsl/server/directives/FileAndResourceDirectivesSpec.scala
  akka-http-tests/src/test/scala/akka/http/scaladsl/server/directives/FutureDirectivesSpec.scala
  akka-http/src/main/scala/akka/http/javadsl/server/Route.scala
  docs/src/main/paradox/migration-guide/migration-guide-10.2.x.md
Labels: tested

#3049 Allow customizing parsing errors
  akka-http-core/src/main/mima-filters/10.1.x.backwards.excludes/configure-parsing-error-response.backwards.excludes
  akka-http-core/src/main/resources/reference.conf
  akka-http-core/src/main/scala/akka/http/ParsingErrorHandler.scala
  akka-http-core/src/main/scala/akka/http/impl/engine/server/HttpServerBluePrint.scala
  akka-http-core/src/main/scala/akka/http/impl/settings/ServerSettingsImpl.scala
  akka-http-core/src/main/scala/akka/http/javadsl/settings/ServerSettings.scala
  akka-http-core/src/main/scala/akka/http/scaladsl/Http.scala
  akka-http-core/src/main/scala/akka/http/scaladsl/settings/ServerSettings.scala
  akka-http-core/src/test/scala/akka/http/impl/engine/server/HttpServerSpec.scala
Labels: tested

#3071 Update github-api to 1.111
  project/plugins.sbt
Labels: tested

#3074 Test cleanup to use AkkaSpecWithMaterializer in more places
  akka-http-core/src/test/scala/akka/http/javadsl/HttpExtensionApiSpec.scala
  akka-http-core/src/test/scala/akka/http/scaladsl/model/HttpEntitySpec.scala
Labels: tested

#3077 docs: update to make HttpServerWithTypedSample more 2.6-style
  build.sbt
  docs/src/main/paradox/routing-dsl/index.md
  docs/src/test/scala/docs/http/scaladsl/HttpServerWithActorsSample.scala
Labels: tested

#3022 Fix server-side cancellation race
  akka-http-core/src/main/mima-filters/10.1.x.backwards.excludes/3022-fix-server-side-cancellation-races.excludes
  akka-http-core/src/main/resources/reference.conf
  akka-http-core/src/main/scala/akka/http/impl/engine/server/HttpServerBluePrint.scala
  akka-http-core/src/main/scala/akka/http/impl/settings/ServerSettingsImpl.scala
  akka-http-core/src/main/scala/akka/http/impl/util/StreamUtils.scala
  akka-http-core/src/main/scala/akka/http/javadsl/settings/ServerSettings.scala
  akka-http-core/src/main/scala/akka/http/scaladsl/Http.scala
  akka-http-core/src/main/scala/akka/http/scaladsl/settings/ServerSettings.scala
  akka-http-core/src/test/scala/akka/http/impl/engine/server/HttpServerSpec.scala
  akka-http-core/src/test/scala/akka/http/impl/engine/server/HttpServerWithExplicitSchedulerSpec.scala
  akka-http-core/src/test/scala/akka/http/scaladsl/ClientServerSpec.scala
Labels: tested

#3084 Update sbt-header to 5.6.0
  project/plugins.sbt
Labels: tested

#3087 core: move ParsingErrorHandler creation to ControllerStage
  akka-http-core/src/main/mima-filters/10.1.x.backwards.excludes/configure-parsing-error-response.excludes
  akka-http-core/src/main/scala/akka/http/impl/engine/server/HttpServerBluePrint.scala
  akka-http-core/src/main/scala/akka/http/impl/settings/ServerSettingsImpl.scala
  akka-http-core/src/main/scala/akka/http/scaladsl/Http.scala
  akka-http-core/src/main/scala/akka/http/scaladsl/settings/ServerSettings.scala
Labels: tested

#3085 Routing DSL: Allow names as alternative to directive combiners
  akka-http/src/main/scala/akka/http/scaladsl/server/Directive.scala
  docs/src/main/paradox/routing-dsl/directives/index.md
  docs/src/main/paradox/routing-dsl/directives/parameter-directives/parameters.md
Labels: tested

#3053 gracefully discard unsupported h2 SETTINGS
  akka-http2-support/src/main/scala/akka/http/impl/engine/http2/framing/Http2FrameParsing.scala
  akka-http2-support/src/test/scala/akka/http/impl/engine/http2/framing/Http2FramingSpec.scala
Labels: tested

#3090 backport: gracefully discard unsupported h2 SETTINGS
  akka-http2-support/src/main/scala/akka/http/impl/engine/http2/framing/Http2FrameParsing.scala
  akka-http2-support/src/test/scala/akka/http/impl/engine/http2/framing/Http2FramingSpec.scala
Labels: tested

#3082 Routing DSL: Names for to symbolic enhancements
  akka-http-tests/src/test/scala/akka/http/scaladsl/server/directives/FormFieldDirectivesSpec.scala
  akka-http-tests/src/test/scala/akka/http/scaladsl/server/directives/ParameterDirectivesSpec.scala
  akka-http-tests/src/test/scala/akka/http/scaladsl/server/directives/PathDirectivesSpec.scala
  akka-http/src/main/scala/akka/http/javadsl/server/directives/FormFieldDirectives.scala
  akka-http/src/main/scala/akka/http/javadsl/server/directives/ParameterDirectives.scala
  akka-http/src/main/scala/akka/http/scaladsl/common/NameReceptacle.scala
  akka-http/src/main/scala/akka/http/scaladsl/server/ExceptionHandler.scala
  akka-http/src/main/scala/akka/http/scaladsl/server/directives/MethodDirectives.scala
  akka-http/src/main/scala/akka/http/scaladsl/server/directives/ParameterDirectives.scala
  akka-http/src/main/scala/akka/http/scaladsl/server/directives/SecurityDirectives.scala
  docs/src/main/paradox/routing-dsl/directives/form-field-directives/formFields.md
  docs/src/main/paradox/routing-dsl/directives/index.md
  docs/src/main/paradox/routing-dsl/directives/parameter-directives/parameters.md
  docs/src/test/scala/docs/http/scaladsl/HttpServerExampleSpec.scala
  docs/src/test/scala/docs/http/scaladsl/server/CaseClassExtractionExamplesSpec.scala
  docs/src/test/scala/docs/http/scaladsl/server/directives/FormFieldDirectivesExamplesSpec.scala
  docs/src/test/scala/docs/http/scaladsl/server/directives/ParameterDirectivesExamplesSpec.scala
Labels: t:http:server:dsl, tested

#3092 Docs: Make Case class extraction work with 2.13
  docs/src/test/scala/docs/http/scaladsl/server/CaseClassExtractionExamplesSpec.scala
Labels: tested

#3083 Update extractClientIP.md to adapt `akka.http.server.remote-address-attribute`
  akka-http/src/main/scala/akka/http/javadsl/server/directives/MiscDirectives.scala
  akka-http/src/main/scala/akka/http/scaladsl/server/directives/MiscDirectives.scala
  docs/src/main/paradox/routing-dsl/directives/misc-directives/extractClientIP.md
Labels: tested

#3014 Route integration testing
  akka-http-testkit/src/main/scala/akka/http/javadsl/testkit/RouteTest.scala
  akka-http-testkit/src/main/scala/akka/http/javadsl/testkit/TestRoute.scala
  akka-http-testkit/src/main/scala/akka/http/scaladsl/testkit/RouteTest.scala
  akka-http-testkit/src/main/scala/akka/http/scaladsl/testkit/RouteTestResultComponent.scala
  akka-http-testkit/src/test/java/akka/http/javadsl/testkit/JUnitRouteTestTest.java
  akka-http-testkit/src/test/scala/akka/http/scaladsl/testkit/ScalatestRouteTestSpec.scala
  akka-http-tests/src/test/scala/akka/http/scaladsl/server/IntegrationRoutingSpec.scala
  akka-http-tests/src/test/scala/akka/http/scaladsl/server/directives/IllegalHeadersIntegrationSpec.scala
  akka-http-tests/src/test/scala/akka/http/scaladsl/server/directives/TimeoutDirectivesSpec.scala
  docs/src/main/paradox/routing-dsl/testkit.md
Labels: validating

#3089 Routing DSL: Allow names to match paths
  akka-http-tests/src/test/scala/akka/http/javadsl/DirectivesConsistencySpec.scala
  akka-http/src/main/scala/akka/http/scaladsl/server/PathMatcher.scala
  docs/src/main/paradox/routing-dsl/path-matchers.md
Labels: t:http:server:dsl, tested

#3094 Fix release issue creation script
  RELEASING.md
  scripts/create-release-issue.sh
Labels: tested

#2962 Fix HeaderParser Unicode issue
  akka-http-core/src/main/scala/akka/http/impl/engine/parsing/HttpHeaderParser.scala
  akka-http-core/src/main/scala/akka/http/impl/engine/parsing/package.scala
  akka-http-core/src/test/scala/akka/http/impl/engine/parsing/HttpHeaderParserSpec.scala
Labels: needs-backport, tested

#3095 10.2.0-M1 release notes
  docs/src/main/paradox/migration-guide/migration-guide-10.2.x.md
  docs/src/main/paradox/release-notes/10.2.x.md
Labels: tested

#3104 Update caffeine to 2.8.2
  project/Dependencies.scala
Labels: tested

#3110 build: bundle scala steward dependencies updates to once a week
  .scala-steward.conf
Labels: tested

#3109 #3050 improve error message about unconsumed entity
  akka-http-core/src/main/scala/akka/http/impl/engine/client/pool/SlotState.scala
  akka-http-core/src/test/scala/akka/http/impl/engine/client/HostConnectionPoolSpec.scala
  docs/src/main/paradox/implications-of-streaming-http-entity.md
Labels: tested

#3101 h2 frame parsing: improve handling of unknown values
  akka-http2-support/src/main/scala/akka/http/impl/engine/http2/Http2Blueprint.scala
  akka-http2-support/src/main/scala/akka/http/impl/engine/http2/Http2Protocol.scala
  akka-http2-support/src/main/scala/akka/http/impl/engine/http2/framing/Http2FrameParsing.scala
  akka-http2-support/src/main/scala/akka/http/scaladsl/Http2.scala
  akka-http2-support/src/main/scala/akka/http/scaladsl/model/http2/Http2SettingsHeader.scala
  akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2FrameProbe.scala
  akka-http2-support/src/test/scala/akka/http/impl/engine/http2/framing/Http2FramingSpec.scala
Labels: tested

#3105 Update specs2-core to 4.9.4
  project/Dependencies.scala
Labels: tested

#3111 Update sbt-paradox-akka to 0.33
  project/plugins.sbt
Labels: tested

#3096 [backport] core: fix parsing of partly cached headers with UTF-8 values
  akka-http-core/src/main/scala/akka/http/impl/engine/parsing/HttpHeaderParser.scala
  akka-http-core/src/main/scala/akka/http/impl/engine/parsing/package.scala
  akka-http-core/src/test/scala/akka/http/impl/engine/parsing/HttpHeaderParserSpec.scala
Labels: tested

#3091 Build: silence warnings for argument adaptation
  project/Common.scala
  project/Dependencies.scala
Labels: tested

#3106 core: header rendering with less indirection
  akka-http-core/src/main/mima-filters/10.1.x.backwards.excludes/internal-RenderSupport-changes.excludes
  akka-http-core/src/main/scala/akka/http/impl/engine/rendering/HttpResponseRendererFactory.scala
  akka-http-core/src/main/scala/akka/http/impl/engine/rendering/RenderSupport.scala
  akka-http-core/src/main/scala/akka/http/scaladsl/model/headers/headers.scala
Labels: tested

#3107 parsing: don't extend from Char => Boolean for CharPredicate
  akka-http-core/src/main/scala/akka/http/scaladsl/model/HttpHeader.scala
  akka-http-core/src/test/scala/akka/http/impl/engine/parsing/HttpHeaderParserSpec.scala
  akka-parsing/src/main/scala/akka/parboiled2/CharPredicate.scala
Labels: tested

#3114 Enable some fatal warnings for docs
  build.sbt
  docs/src/main/paradox/.htaccess
  docs/src/main/paradox/routing-dsl/directives/alphabetically.md
  docs/src/main/paradox/routing-dsl/directives/file-upload-directives/index.md
  docs/src/main/paradox/routing-dsl/directives/file-upload-directives/uploadedFile.md
  docs/src/test/java/docs/http/javadsl/server/directives/FileUploadDirectivesExamplesTest.java
  docs/src/test/scala/docs/http/scaladsl/HttpClientDecodingExampleSpec.scala
  docs/src/test/scala/docs/http/scaladsl/HttpClientExampleSpec.scala
  docs/src/test/scala/docs/http/scaladsl/HttpServerExampleSpec.scala
  docs/src/test/scala/docs/http/scaladsl/HttpsExamplesSpec.scala
  docs/src/test/scala/docs/http/scaladsl/SprayJsonExampleSpec.scala
  docs/src/test/scala/docs/http/scaladsl/WebSocketClientExampleSpec.scala
  docs/src/test/scala/docs/http/scaladsl/server/ExceptionHandlerExamplesSpec.scala
  docs/src/test/scala/docs/http/scaladsl/server/HttpsServerExampleSpec.scala
  docs/src/test/scala/docs/http/scaladsl/server/directives/FileUploadDirectivesExamplesSpec.scala
  docs/src/test/scala/docs/http/scaladsl/server/directives/JsonStreamingFullExamples.scala
Labels: tested

#3079 Docs: routing DSL compared with Play routes
  docs/src/main/paradox/routing-dsl/directives/parameter-directives/parameters.md
  docs/src/main/paradox/routing-dsl/index.md
  docs/src/main/paradox/routing-dsl/overview.md
  docs/src/main/paradox/routing-dsl/play-comparison.md
  docs/src/main/paradox/routing-dsl/routes.md
  docs/src/test/java/docs/http/javadsl/server/testkit/PlayRoutesComparisonTest.java
  docs/src/test/scala/docs/http/scaladsl/server/PlayRoutesComparisonSpec.scala
Labels: tested

#3120 Remove deprecated FormFieldDirectives methods
  akka-http/src/main/mima-filters/10.1.x.backwards.excludes/remove-deprecated-formfielddirectives-methods.backwards.excludes
  akka-http/src/main/scala/akka/http/scaladsl/server/directives/FormFieldDirectives.scala
Labels: tested

#3119 Remove deprecated methods taking implicit materializers
  akka-http-core/src/main/mima-filters/10.1.x.backwards.excludes/remove-deprecated-methods-taking-implicit-materializers.backwards.excludes
  akka-http-core/src/main/scala/akka/http/scaladsl/Http.scala
Labels: tested

#3118 Remove uploadedFile (deprecated in 10.0.11)
  akka-http-tests/src/test/scala/akka/http/scaladsl/server/directives/FileUploadDirectivesSpec.scala
  akka-http/src/main/mima-filters/10.1.x.backwards.excludes/removed-deprecated-uploadedFile-directive.backwards.excludes
  akka-http/src/main/scala/akka/http/javadsl/server/directives/FileUploadDirectives.scala
  akka-http/src/main/scala/akka/http/scaladsl/server/directives/FileUploadDirectives.scala
  docs/src/test/java/docs/http/javadsl/server/directives/FileUploadDirectivesExamplesTest.java
Labels: tested

#3121 Docs: show symbolic Akka verson for dependencies
  build.sbt
  docs/src/main/paradox/introduction.md
  docs/src/main/paradox/routing-dsl/testkit.md
  project/AkkaDependency.scala
Labels: t:docs, tested

#3123 Scala 2.13 errors/warnings
  akka-http-bench-jmh/src/main/scala/akka/BenchRunner.scala
  build.sbt
  docs/src/test/scala/docs/http/scaladsl/HttpServerExampleSpec.scala
  docs/src/test/scala/docs/http/scaladsl/HttpServerWithActorsSample.scala
  docs/src/test/scala/docs/http/scaladsl/SprayJsonExampleSpec.scala
  docs/src/test/scala/docs/http/scaladsl/WebSocketClientExampleSpec.scala
Labels: tested
