Repository akka/akka-http, pull requests merged in 2020-01, with the labels that each got.

#2864 Small typo in docs/src/main/paradox/common/marshalling.md
  docs/src/main/paradox/common/marshalling.md
Labels: tested

#2862 Update sbt to 1.3.6
  project/build.properties
Labels: tested

#2863 Update sbt-bintray to 0.5.6
  project/plugins.sbt
Labels: tested

#2873 Use one Jackson version field
  build.sbt
  project/Dependencies.scala
Labels: tested

#2869 Drop Scala 2.11
  build.sbt
  docs/src/main/paradox/routing-dsl/index.md
  docs/src/test/scala/docs/http/scaladsl/HttpServerWithTypedSample.scala
  project/AkkaDependency.scala
  project/Dependencies.scala
Labels: tested

#2875 Update specs2-core to 4.8.2
  project/Dependencies.scala
Labels: tested

#2876 Update sbt-header to 5.4.0
  project/plugins.sbt
Labels: tested

#2860 Update scalacheck to 1.14.3
  project/Dependencies.scala
Labels: tested

#2866 Update sbt-paradox-akka to 0.29
  project/plugins.sbt
Labels: tested

#2868 Don't automatically update Akka
  .scala-steward.conf
Labels: tested

#2871 Update jackson dependency to 2.10.2
  project/Dependencies.scala
Labels: validating

#2878 build: cache coursier directory in travis
  .travis.yml
Labels: tested

#2874 Update reflections to 0.9.12
  project/Dependencies.scala
Labels: tested

#2853 = only catch NonFatal Exceptions
  akka-http-core/src/main/scala/akka/http/impl/engine/parsing/HttpResponseParser.scala
Labels: tested

#2880 build: cache modern coursier cache directory in travis
  .travis.yml
Labels: tested

#2865 Update junit to 4.13
  project/Dependencies.scala
Labels: tested

#2881 build: always use latest for compatibility tests
  build.sbt
  project/MiMa.scala
Labels: tested

#2879 Update specs2-core to 4.8.3
  project/Dependencies.scala
Labels: tested

#2851 Update scalatest to 3.1.0
  akka-http-core/src/test/scala/akka/http/impl/engine/parsing/BoyerMooreSpec.scala
  akka-http-core/src/test/scala/akka/http/impl/engine/parsing/ContentLengthHeaderParserSpec.scala
  akka-http-core/src/test/scala/akka/http/impl/engine/parsing/HttpHeaderParserSpec.scala
  akka-http-core/src/test/scala/akka/http/impl/engine/parsing/RequestParserSpec.scala
  akka-http-core/src/test/scala/akka/http/impl/engine/parsing/ResponseParserSpec.scala
  akka-http-core/src/test/scala/akka/http/impl/engine/rendering/RequestRendererSpec.scala
  akka-http-core/src/test/scala/akka/http/impl/engine/rendering/ResponseRendererSpec.scala
  akka-http-core/src/test/scala/akka/http/impl/engine/ws/WSTestSetupBase.scala
  akka-http-core/src/test/scala/akka/http/impl/model/parser/HttpHeaderSpec.scala
  akka-http-core/src/test/scala/akka/http/impl/util/ByteStringParserInputSpec.scala
  akka-http-core/src/test/scala/akka/http/impl/util/RenderingSpec.scala
  akka-http-core/src/test/scala/akka/http/javadsl/ConnectHttpSpec.scala
  akka-http-core/src/test/scala/akka/http/javadsl/ConnectionContextSpec.scala
  akka-http-core/src/test/scala/akka/http/javadsl/HttpExtensionApiSpec.scala
  akka-http-core/src/test/scala/akka/http/javadsl/JavaInitializationSpec.scala
  akka-http-core/src/test/scala/akka/http/javadsl/model/JavaApiSpec.scala
  akka-http-core/src/test/scala/akka/http/javadsl/model/JavaApiTestCaseSpecs.scala
  akka-http-core/src/test/scala/akka/http/javadsl/model/MultipartsSpec.scala
  akka-http-core/src/test/scala/akka/http/scaladsl/ClientServerSpec.scala
  akka-http-core/src/test/scala/akka/http/scaladsl/ClientSpec.scala
  akka-http-core/src/test/scala/akka/http/scaladsl/SslConfigWarningsSpec.scala
  akka-http-core/src/test/scala/akka/http/scaladsl/TightRequestTimeoutSpec.scala
  akka-http-core/src/test/scala/akka/http/scaladsl/model/DateTimeSpec.scala
  akka-http-core/src/test/scala/akka/http/scaladsl/model/HttpEntitySpec.scala
  akka-http-core/src/test/scala/akka/http/scaladsl/model/HttpMessageSpec.scala
  akka-http-core/src/test/scala/akka/http/scaladsl/model/HttpMethodsSpec.scala
  akka-http-core/src/test/scala/akka/http/scaladsl/model/MultipartSpec.scala
  akka-http-core/src/test/scala/akka/http/scaladsl/model/SerializabilitySpec.scala
  akka-http-core/src/test/scala/akka/http/scaladsl/model/TurkishISpec.scala
  akka-http-core/src/test/scala/akka/http/scaladsl/model/UriSpec.scala
  akka-http-core/src/test/scala/akka/http/scaladsl/model/headers/HeaderSpec.scala
  akka-http-core/src/test/scala/akka/http/scaladsl/model/sse/ServerSentEventSpec.scala
  akka-http-core/src/test/scala/akka/http/scaladsl/settings/SettingsEqualitySpec.scala
  akka-http-core/src/test/scala/akka/http/scaladsl/util/FastFutureSpec.scala
  akka-http-core/src/test/scala/akka/testkit/AkkaSpec.scala
  akka-http-core/src/test/scala/io/akka/integrationtest/http/HttpModelIntegrationSpec.scala
  akka-http-marshallers-scala/akka-http-spray-json/src/test/scala/akka/http/scaladsl/marshallers/sprayjson/SprayJsonSupportSpec.scala
  akka-http-testkit/src/main/scala/akka/http/scaladsl/testkit/ScalatestUtils.scala
  akka-http-tests/src/multi-jvm/scala/akka/http/STMultiNodeSpec.scala
  akka-http-tests/src/multi-jvm/scala/akka/remote/testkit/MultiNodeConfig.scala
  akka-http-tests/src/multi-jvm/scala/org/scalatest/extra/QuietReporter.scala
  docs/src/main/paradox/release-notes/10.2.x.md
  docs/src/main/paradox/release-notes/index.md
  project/Dependencies.scala
Labels: tested

#2890 Update sbt to 1.3.7
  project/build.properties
Labels: tested

#2891 http2: fix HeaderCompression updating table size without giving notice to peer
  akka-http2-support/src/main/scala/akka/http/impl/engine/http2/hpack/HeaderCompression.scala
  akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2ServerSpec.scala
Labels: needs-backport, tested

#2899 Add the remote address in parse errors when possible
  akka-http-core/src/main/scala/akka/http/impl/engine/parsing/HttpRequestParser.scala
Labels: needs-backport, tested

#2901 jackson: better JSON validation error when unmarshalling
  akka-http-marshallers-java/akka-http-jackson/src/main/java/akka/http/javadsl/marshallers/jackson/Jackson.java
  akka-http-marshallers-java/akka-http-jackson/src/test/java/akka/http/javadsl/marshallers/jackson/JacksonTest.java
  project/Dependencies.scala
Labels: tested

#2904 build: update github-api to 1.103
  project/ValidatePullRequest.scala
  project/plugins.sbt
Labels: validating

#2905 Merge pull request #2905 from jrudolph/improve-outgoing-request-stream-error
  akka-http-core/src/main/scala/akka/http/impl/engine/client/OutgoingConnectionBlueprint.scala
  akka-http-core/src/test/scala/akka/http/impl/engine/client/HostConnectionPoolSpec.scala
Labels: tested

#2906 Merge pull request #2906 from jrudolph/1747-fix-HttpServerSpec-failure
  akka-http-core/src/test/scala/akka/http/impl/engine/server/HttpServerSpec.scala
Labels: tested

#2913 Update sbt-unidoc to 0.4.3
  project/plugins.sbt
Labels: tested
