Repository akka/akka-http, pull requests merged in 2020-05, with the labels that each got.

#3078 Actor interop Java example
  akka-http/src/main/scala/akka/http/javadsl/server/Route.scala
  docs/src/main/paradox/introduction.md
  docs/src/main/paradox/routing-dsl/index.md
  docs/src/test/java/docs/http/javadsl/HttpServerWithActorsSample.java
  docs/src/test/java/docs/http/javadsl/JobRepository.java
  docs/src/test/java/docs/http/javadsl/JobRoutes.java
  docs/src/test/scala/docs/http/scaladsl/HttpServerWithActorsSample.scala
Labels: tested

#3127 Fix more 2.13 warnings
  build.sbt
  docs/src/main/paradox/client-side/connection-level.md
  docs/src/main/paradox/client-side/request-level.md
  docs/src/main/paradox/client-side/websocket-support.md
  docs/src/main/paradox/introduction.md
  docs/src/main/paradox/routing-dsl/index.md
  docs/src/main/paradox/routing-dsl/overview.md
  docs/src/test/scala/docs/http/scaladsl/HttpClientCollectingHeaders.scala
  docs/src/test/scala/docs/http/scaladsl/HttpClientExampleSpec.scala
  docs/src/test/scala/docs/http/scaladsl/HttpClientOutgoingConnection.scala
  docs/src/test/scala/docs/http/scaladsl/HttpClientSingleRequest.scala
  docs/src/test/scala/docs/http/scaladsl/HttpServerBindingFailure.scala
  docs/src/test/scala/docs/http/scaladsl/HttpServerExampleSpec.scala
  docs/src/test/scala/docs/http/scaladsl/HttpServerHighLevel.scala
  docs/src/test/scala/docs/http/scaladsl/HttpServerLowLevel.scala
  docs/src/test/scala/docs/http/scaladsl/HttpServerRoutingMinimal.scala
  docs/src/test/scala/docs/http/scaladsl/HttpServerStreamingRandomNumbers.scala
  docs/src/test/scala/docs/http/scaladsl/HttpServerWithActorInteraction.scala
  docs/src/test/scala/docs/http/scaladsl/SingleWebSocketRequest.scala
  docs/src/test/scala/docs/http/scaladsl/SprayJsonExample2.scala
  docs/src/test/scala/docs/http/scaladsl/SprayJsonExampleSpec.scala
  docs/src/test/scala/docs/http/scaladsl/WebSocketClientExampleSpec.scala
  docs/src/test/scala/docs/http/scaladsl/WebSocketClientFlow.scala
Labels: tested

#3130 Fix more Scala 2.13 warnings
  akka-http-core/src/main/scala/akka/http/scaladsl/model/ws/Message.scala
  akka-http-core/src/test/scala/akka/http/impl/engine/rendering/ResponseRendererSpec.scala
  akka-http-core/src/test/scala/akka/testkit/AkkaSpec.scala
  akka-http-core/src/test/scala/akka/testkit/Coroner.scala
  akka-http-testkit/src/main/scala/akka/http/scaladsl/testkit/TestFrameworkInterface.scala
  akka-parsing/src/main/scala/akka/shapeless/hlists.scala
  docs/src/test/scala/docs/http/scaladsl/server/directives/HeaderDirectivesExamplesSpec.scala
Labels: tested

#3124 core: convert ClientServerSpec to use AkkaSpecWithMaterializer
  akka-http-core/src/test/scala/akka/http/scaladsl/ClientServerSpec.scala
Labels: tested

#3132 build: update jackson-dataformat-xml from 2.10.3 to 2.10.4
  .scala-steward.conf
  project/Dependencies.scala
Labels: tested

#3108 Reuse UriParser In HttpRequestParser
  akka-http-core/src/main/scala/akka/http/impl/engine/parsing/HttpRequestParser.scala
  akka-http-core/src/main/scala/akka/http/impl/model/parser/UriParser.scala
  akka-http-core/src/main/scala/akka/http/impl/util/ByteStringParserInput.scala
  akka-parsing/src/main/scala/akka/parboiled2/Parser.scala
  akka-parsing/src/main/scala/akka/parboiled2/RuleDSLBasics.scala
Labels: tested

#3126 build: build with Scala 2.13 by default
  project/Dependencies.scala
Labels: tested

#3125 [release 10.1] http2: support ALPN natively on JDK >= 8u252
  akka-http2-support/src/main/scala/akka/http/impl/engine/http2/Http2AlpnSupport.scala
  docs/src/main/paradox/release-notes/10.1.x.md
  docs/src/main/paradox/server-side/http2.md
  project/Dependencies.scala
Labels: tested

#3117 Support native ALPN in JDK >=8u251
  akka-http2-support/src/main/scala/akka/http/impl/engine/http2/Http2AlpnSupport.scala
  akka-http2-support/src/main/scala/akka/http/scaladsl/Http2.scala
  akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2ServerSpec.scala
  akka-http2-support/src/test/scala/akka/http/scaladsl/Http2ServerTest.scala
  build.sbt
  docs/src/main/paradox/migration-guide/migration-guide-10.2.x.md
  docs/src/main/paradox/release-notes/10.1.x.md
  docs/src/main/paradox/server-side/http2.md
  project/Dependencies.scala
Labels: tested

#3115 Provide Route.toFunction as alternative to Route.asyncHandler
  akka-http/src/main/scala/akka/http/scaladsl/server/Route.scala
  docs/src/test/scala/docs/http/scaladsl/Http2Spec.scala
  docs/src/test/scala/docs/http/scaladsl/server/directives/JsonStreamingFullExamples.scala
Labels: tested

#3099 Routing DSL: style guide
  docs/src/main/paradox/routing-dsl/index.md
  docs/src/main/paradox/routing-dsl/style-guide.md
  docs/src/test/java/docs/http/javadsl/server/directives/StyleGuideExamplesTest.java
  docs/src/test/scala/docs/http/scaladsl/server/directives/StyleGuideExamplesSpec.scala
Labels: t:docs, t:routing, tested

#3075 Use SystemMaterializer in AkkaSpecWithMaterializer
  akka-http-core/src/test/scala/akka/http/impl/engine/client/ClientCancellationSpec.scala
  akka-http-core/src/test/scala/akka/http/impl/engine/server/HttpServerSpec.scala
  akka-http-core/src/test/scala/akka/http/impl/util/AkkaSpecWithMaterializer.scala
  akka-http-core/src/test/scala/akka/http/impl/util/ExampleHttpContexts.scala
  akka-http-testkit/src/main/scala/akka/http/scaladsl/testkit/RouteTest.scala
Labels: tested

#3140 Publish 10.1 snapshots
  .travis.yml
Labels: tested

#3141 Make RouteTest compile again
  akka-http-testkit/src/main/scala/akka/http/scaladsl/testkit/RouteTest.scala
Labels: tested

#3144 [backport] core: fix EOL detection for body part parsing
  akka-http-core/src/main/scala/akka/http/impl/engine/parsing/BodyPartParser.scala
  akka-http-tests/src/test/scala/akka/http/scaladsl/unmarshalling/MultipartUnmarshallersSpec.scala
Labels: tested

#3145 Revert "SystemMaterializer in AkkaSpecWithMaterializer (#3075)"
  akka-http-core/src/test/scala/akka/http/impl/engine/client/ClientCancellationSpec.scala
  akka-http-core/src/test/scala/akka/http/impl/engine/server/HttpServerSpec.scala
  akka-http-core/src/test/scala/akka/http/impl/util/AkkaSpecWithMaterializer.scala
  akka-http-core/src/test/scala/akka/http/impl/util/ExampleHttpContexts.scala
  akka-http-testkit/src/main/scala/akka/http/scaladsl/testkit/RouteTest.scala
Labels: tested

#3146 10.1.12 release notes
  docs/src/main/paradox/release-notes/10.1.x.md
Labels: tested

#3149 build: update scalatest from 3.1.1 to 3.1.2
  project/Dependencies.scala
Labels: tested

#3153 Add 10.1.12 to MiMa list
  akka-http-core/src/main/mima-filters/10.1.x.backwards.excludes/1354-add-HttpCookie-SameSite-attribute.backwards.excludes
  akka-http-core/src/main/mima-filters/10.1.x.backwards.excludes/1500-attributes.excludes
  akka-http-core/src/main/mima-filters/10.1.x.backwards.excludes/2095-no-UseHttp2.backwards.excludes
  akka-http-core/src/main/mima-filters/10.1.x.backwards.excludes/query-string-encoding.backwards.excludes
  project/MiMa.scala
Labels: tested

#3152 [release-10.1] Add 10.1.12 to mima
  project/MiMa.scala
Labels: tested

#3151 core: use SystemMaterializer in AkkaSpecWithMaterializer
  akka-http-core/src/main/scala/akka/http/impl/engine/client/PoolMasterActor.scala
  akka-http-core/src/test/scala/akka/http/impl/engine/client/ClientCancellationSpec.scala
  akka-http-core/src/test/scala/akka/http/impl/engine/server/HttpServerSpec.scala
  akka-http-core/src/test/scala/akka/http/impl/util/AkkaSpecWithMaterializer.scala
  akka-http-core/src/test/scala/akka/http/impl/util/ExampleHttpContexts.scala
  akka-http-core/src/test/scala/akka/http/scaladsl/ClientServerSpec.scala
  akka-http-testkit/src/main/scala/akka/http/scaladsl/testkit/RouteTest.scala
Labels: tested

#3076 Fix request body line parsing: Issue #2581
  akka-http-core/src/main/scala/akka/http/impl/engine/parsing/BodyPartParser.scala
  akka-http-tests/src/test/scala/akka/http/scaladsl/unmarshalling/MultipartUnmarshallersSpec.scala
Labels: 2 - pick next, needs-backport, tested

#3154 Forward port of 10.1.12 release notes
  docs/src/main/paradox/release-notes/10.1.x.md
  scripts/release-train-issue-template.md
Labels: tested

#3158 Core: Allow multiple Host headers in responses
  akka-http-core/src/main/mima-filters/10.1.x.backwards.excludes/3158-allow-multiple-host-headers.backwards.excludes
  akka-http-core/src/main/scala/akka/http/impl/engine/parsing/HttpMessageParser.scala
  akka-http-core/src/main/scala/akka/http/impl/engine/parsing/HttpRequestParser.scala
  akka-http-core/src/main/scala/akka/http/impl/engine/parsing/HttpResponseParser.scala
  akka-http-core/src/test/scala/akka/http/impl/engine/parsing/RequestParserSpec.scala
  akka-http-core/src/test/scala/akka/http/impl/engine/parsing/ResponseParserSpec.scala
Labels: tested

#3156 core: simplify `superPool` and `clientFlow`
  akka-http-core/src/main/mima-filters/10.1.x.backwards.excludes/remove-internal-Http-impl-methods.excludes
  akka-http-core/src/main/scala/akka/http/javadsl/Http.scala
  akka-http-core/src/main/scala/akka/http/scaladsl/Http.scala
Labels: tested

#3160 core: decrease idle timeout in ClientServerSpec
  akka-http-core/src/test/scala/akka/http/scaladsl/ClientServerSpec.scala
Labels: tested

#3169 build: update caffeine from 2.8.2 to 2.8.3
  project/Dependencies.scala
Labels: tested

#3172 Make scalatest versions consistent
  project/Dependencies.scala
Labels: tested

#3174 Deprecate Remote-Address header
  akka-http-core/src/main/java/akka/http/javadsl/model/headers/RemoteAddress.java
  akka-http-core/src/main/resources/reference.conf
  akka-http-core/src/main/scala/akka/http/impl/engine/server/HttpServerBluePrint.scala
  akka-http-core/src/main/scala/akka/http/javadsl/settings/ServerSettings.scala
  akka-http-core/src/main/scala/akka/http/scaladsl/Http.scala
  akka-http-core/src/main/scala/akka/http/scaladsl/model/headers/headers.scala
  akka-http-core/src/main/scala/akka/http/scaladsl/settings/ServerSettings.scala
  akka-http-tests/src/test/scala/akka/http/scaladsl/server/directives/MiscDirectivesSpec.scala
  akka-http2-support/src/main/scala/akka/http/impl/engine/http2/RequestParsing.scala
  docs/src/test/java/docs/http/javadsl/server/directives/MiscDirectivesExamplesTest.java
  docs/src/test/scala/docs/http/scaladsl/server/directives/MiscDirectivesExamplesSpec.scala
Labels: tested

#3173 Make X-Real-Ip take precedence over Remote-Address
  akka-http-tests/src/test/scala/akka/http/scaladsl/server/directives/MiscDirectivesSpec.scala
  akka-http/src/main/scala/akka/http/scaladsl/server/directives/MiscDirectives.scala
  docs/src/main/paradox/migration-guide/migration-guide-10.2.x.md
  docs/src/main/paradox/routing-dsl/directives/misc-directives/extractClientIP.md
Labels: tested

#2560 Hide body and headers by default in `HttpRequest#toString` and `HttpResponse#toString`
  akka-http-core/src/main/mima-filters/10.1.11.backwards.excludes/2560-hide-body-and-headers-in-tostring.excludes
  akka-http-core/src/main/scala/akka/http/scaladsl/model/HttpHeader.scala
  akka-http-core/src/main/scala/akka/http/scaladsl/model/headers/headers.scala
  akka-http-core/src/test/scala/akka/http/impl/engine/client/HttpsProxyGraphStageSpec.scala
  akka-http-core/src/test/scala/akka/http/impl/engine/parsing/HttpHeaderParserSpec.scala
  akka-http-core/src/test/scala/akka/http/impl/model/parser/HttpHeaderSpec.scala
  docs/src/main/paradox/common/http-model.md
  docs/src/test/java/docs/http/javadsl/HttpRequestDetailedStringExampleTest.java
  docs/src/test/java/docs/http/javadsl/HttpResponseDetailedStringExampleTest.java
  docs/src/test/scala/docs/http/scaladsl/HttpRequestDetailedStringExampleSpec.scala
  docs/src/test/scala/docs/http/scaladsl/HttpResponseDetailedStringExampleSpec.scala
Labels: tested

#3098 core: move max-content-length definition from top to server/client
  akka-http-core/src/main/mima-filters/10.1.x.backwards.excludes/3098-remove-max-content-length-from-top-level-parsing.excludes
  akka-http-core/src/main/resources/reference.conf
  akka-http-core/src/main/scala/akka/http/impl/settings/ParserSettingsImpl.scala
  akka-http-core/src/main/scala/akka/http/impl/util/EnhancedConfig.scala
  akka-http-core/src/main/scala/akka/http/javadsl/settings/ParserSettings.scala
  akka-http-core/src/main/scala/akka/http/scaladsl/settings/ParserSettings.scala
  akka-http-core/src/test/scala/akka/http/impl/engine/client/HttpConfigurationSpec.scala
  akka-http-core/src/test/scala/akka/http/impl/engine/client/PrepareResponseSpec.scala
  akka-http-tests/src/test/scala/akka/http/scaladsl/CustomMediaTypesSpec.scala
  akka-http-tests/src/test/scala/akka/http/scaladsl/CustomStatusCodesSpec.scala
  akka-http-tests/src/test/scala/akka/http/scaladsl/server/SizeLimitSpec.scala
  docs/src/main/paradox/migration-guide/migration-guide-10.2.x.md
  docs/src/test/java/docs/http/javadsl/CustomMediaTypesExampleTest.java
  docs/src/test/java/docs/http/javadsl/CustomStatusCodesExampleTest.java
  docs/src/test/java/docs/http/javadsl/server/directives/CustomHttpMethodExamplesTest.java
  docs/src/test/scala/docs/http/scaladsl/server/directives/CustomHttpMethodSpec.scala
Labels: tested

#3165 Add sbt-reproducible-builds
  build.sbt
  project/plugins.sbt
Labels: tested

#3180 build: update caffeine from 2.8.3 to 2.8.4
  project/Dependencies.scala
Labels: tested

#3181 Remove unnecessary backward compatibility exclusion
  akka-http-core/src/main/mima-filters/10.1.11.backwards.excludes/2560-hide-body-and-headers-in-tostring.excludes
Labels: tested

#3177 Silence JavaConverters warnings
  project/Common.scala
Labels: tested

#3142 Add coordinated shutdown support
  akka-http-core/src/main/scala/akka/http/javadsl/ServerBinding.scala
  akka-http-core/src/main/scala/akka/http/scaladsl/Http.scala
  docs/src/main/paradox/client-side/host-level.md
  docs/src/main/paradox/client-side/index.md
  docs/src/main/paradox/client-side/request-level.md
  docs/src/main/paradox/server-side/graceful-termination.md
  docs/src/test/java/docs/http/javadsl/server/ServerShutdownExampleTest.java
  docs/src/test/scala/docs/http/scaladsl/server/ServerShutdownExampleSpec.scala
Labels: t:docs, tested

#3182 core: mark SensitiveHttpHeader.toString as final
  akka-http-core/src/main/scala/akka/http/scaladsl/model/HttpHeader.scala
Labels: tested

#3183 Avoid warning in HTTP/2 code and add more logging
  akka-http2-support/src/main/scala/akka/http/impl/engine/http2/Http2ServerDemux.scala
  akka-http2-support/src/main/scala/akka/http/impl/engine/http2/Http2StreamHandling.scala
Labels: tested

#3197 core: remove some long deprecated methods
  akka-http-core/src/main/java/akka/http/javadsl/model/HttpMethod.java
  akka-http-core/src/main/java/akka/http/javadsl/model/HttpMethods.java
  akka-http-core/src/main/mima-filters/10.1.x.backwards.excludes/remove-deprecated-methods.excludes
  akka-http-core/src/main/scala/akka/http/javadsl/HostConnectionPool.scala
  akka-http-core/src/main/scala/akka/http/javadsl/settings/ConnectionPoolSettings.scala
  akka-http-core/src/main/scala/akka/http/scaladsl/ConnectionContext.scala
  akka-http-core/src/main/scala/akka/http/scaladsl/Http.scala
  akka-http-core/src/main/scala/akka/http/scaladsl/model/HttpMethod.scala
  akka-http-core/src/test/scala/akka/http/javadsl/HttpExtensionApiSpec.scala
Labels: tested

#3194 http: remove deprecated Route.seal
  akka-http/src/main/mima-filters/10.1.x.backwards.excludes/remove-deprecated-javadsl-Route-seal.excludes
  akka-http/src/main/scala/akka/http/javadsl/server/Route.scala
  akka-http/src/main/scala/akka/http/javadsl/server/directives/RouteAdapter.scala
Labels: tested

#3198 core: remove getDefaultPort and its usages
  akka-http-core/src/main/mima-filters/10.1.x.backwards.excludes/remove-getDefaultPort.excludes
  akka-http-core/src/main/scala/akka/http/javadsl/ConnectionContext.scala
  akka-http-core/src/main/scala/akka/http/scaladsl/ConnectionContext.scala
  akka-http-core/src/main/scala/akka/http/scaladsl/Http.scala
Labels: tested

#3199 core: remove deprecated javadsl entrypoints taking Materializer
  akka-http-core/src/main/mima-filters/10.1.x.backwards.excludes/remove-javadsl-entrypoints-with-materializer.excludes
  akka-http-core/src/main/scala/akka/http/javadsl/Http.scala
  akka-http-core/src/test/scala/akka/http/javadsl/HttpExtensionApiSpec.scala
  akka-http-tests/src/test/java/akka/http/javadsl/HttpAPIsTest.java
  docs/src/test/java/docs/http/javadsl/CustomMediaTypesExampleTest.java
  docs/src/test/java/docs/http/javadsl/CustomStatusCodesExampleTest.java
  docs/src/test/java/docs/http/javadsl/HttpClientDecodingExampleTest.java
  docs/src/test/java/docs/http/javadsl/server/HttpServerExampleDocTest.java
  docs/src/test/java/docs/http/javadsl/server/directives/CustomHttpMethodExamplesTest.java
  docs/src/test/java/docs/http/javadsl/server/directives/MethodDirectivesExamplesTest.java
  docs/src/test/java/docs/http/javadsl/server/directives/SchemeDirectivesExamplesTest.java
  docs/src/test/java/docs/http/javadsl/server/directives/TimeoutDirectivesExamplesTest.java
Labels: tested

#3196 http: remove deprecated entity streaming marshaller
  akka-http-tests/src/test/scala/akka/http/scaladsl/server/EntityStreamingSpec.scala
  akka-http/src/main/mima-filters/10.1.x.backwards.excludes/remove-EntityStreaming-method.excludes
  akka-http/src/main/scala/akka/http/scaladsl/marshalling/PredefinedToResponseMarshallers.scala
Labels: tested
