Repository akka/akka-http, pull requests merged in 2020-10, with the labels that each got.

#3456 core: reenable lingerTimeout
  akka-http-core/src/main/scala/akka/http/impl/engine/server/HttpServerBluePrint.scala
  akka-http-core/src/main/scala/akka/http/impl/engine/server/ServerTerminator.scala
  akka-http-core/src/main/scala/akka/http/impl/util/StreamUtils.scala
  akka-http-core/src/main/scala/akka/http/scaladsl/Http.scala
  akka-http-core/src/test/scala/akka/http/impl/engine/server/HttpServerSpec.scala
  akka-http-core/src/test/scala/akka/http/scaladsl/ClientServerSpec.scala
  akka-http-core/src/test/scala/akka/http/scaladsl/GracefulTerminationSpec.scala
Labels: needs-backport, regression, tested

#3472 Expose the SslSession via an attribute
  akka-http-core/src/main/java/akka/http/javadsl/model/AttributeKeys.java
  akka-http-core/src/main/mima-filters/10.2.0.backwards.excludes/ssl-session-attribute.excludes
  akka-http-core/src/main/resources/reference.conf
  akka-http-core/src/main/scala/akka/http/impl/engine/client/HttpsProxyGraphStage.scala
  akka-http-core/src/main/scala/akka/http/impl/engine/client/OutgoingConnectionBlueprint.scala
  akka-http-core/src/main/scala/akka/http/impl/engine/parsing/HttpMessageParser.scala
  akka-http-core/src/main/scala/akka/http/impl/engine/parsing/HttpRequestParser.scala
  akka-http-core/src/main/scala/akka/http/impl/engine/parsing/HttpResponseParser.scala
  akka-http-core/src/main/scala/akka/http/impl/engine/parsing/ParserOutput.scala
  akka-http-core/src/main/scala/akka/http/impl/engine/ws/WebSocketClientBlueprint.scala
  akka-http-core/src/main/scala/akka/http/impl/settings/ParserSettingsImpl.scala
  akka-http-core/src/main/scala/akka/http/javadsl/model/SslSessionInfo.scala
  akka-http-core/src/main/scala/akka/http/javadsl/settings/ParserSettings.scala
  akka-http-core/src/main/scala/akka/http/scaladsl/model/AttributeKeys.scala
  akka-http-core/src/main/scala/akka/http/scaladsl/model/SslSessionInfo.scala
  akka-http-core/src/main/scala/akka/http/scaladsl/settings/ParserSettings.scala
  akka-http-core/src/test/java/akka/http/javadsl/model/HttpMessageTest.java
  akka-http-core/src/test/scala/akka/http/impl/engine/client/PrepareResponseSpec.scala
  akka-http-core/src/test/scala/akka/http/impl/engine/client/TlsEndpointVerificationSpec.scala
  akka-http-core/src/test/scala/akka/http/impl/engine/parsing/ResponseParserSpec.scala
  akka-http-core/src/test/scala/akka/http/scaladsl/model/HttpMessageSpec.scala
  akka-http2-support/src/main/scala/akka/http/impl/engine/http2/RequestParsing.scala
Labels: tested

#3475 build: update sbt-mima-plugin from 0.7.0 to 0.8.0
  akka-http-core/src/main/mima-filters/10.1.x.backwards.excludes/remove-getDefaultPort.excludes
  akka-http/src/main/mima-filters/10.1.8.backwards.excludes
  project/ValidatePullRequest.scala
  project/plugins.sbt
Labels: tested

#3492 Document requiring client authentication
  docs/src/main/paradox/server-side/server-https-support.md
  docs/src/test/java/docs/http/javadsl/server/HttpsServerExampleTest.java
  docs/src/test/scala/docs/http/scaladsl/server/HttpsServerExampleSpec.scala
Labels: tested

#3488 Update websocket docs to describe attribute
  docs/src/main/paradox/server-side/websocket-support.md
  docs/src/test/java/docs/http/javadsl/server/WebSocketCoreExample.java
  docs/src/test/scala/docs/http/scaladsl/server/WebSocketExampleSpec.scala
Labels: tested

#3494 10.2.1 release notes
  docs/src/main/paradox/release-notes/10.2.x.md
Labels: tested

#3496 Add examples of testing actor interactions
  build.sbt
  docs/src/main/paradox/routing-dsl/testkit.md
  docs/src/test/java/docs/http/javadsl/server/testkit/MyAppWithActor.java
  docs/src/test/java/docs/http/javadsl/server/testkit/TestKitWithActorTest.java
  docs/src/test/scala/docs/http/scaladsl/server/TestKitWithActorSpec.scala
Labels: tested

#3499 build: add 10.2.1 to MiMa
  project/MiMa.scala
Labels: tested

#3497 tests: widen EntityStreamingSpec patience
  akka-http-tests/src/test/scala/akka/http/scaladsl/server/EntityStreamingSpec.scala
Labels: tested

#3500 [backport] tests: widen EntityStreamingSpec patience
  akka-http-tests/src/test/scala/akka/http/scaladsl/server/EntityStreamingSpec.scala
Labels: tested

#3498 Some tweaks to the release checklist
  scripts/release-train-issue-template.md
Labels: tested

#3507 Don't upgrade akka via scala-steward
  .scala-steward.conf
Labels: tested

#3506 http2: use LogHelper in demux classes
  akka-http2-support/src/main/scala/akka/http/impl/engine/http2/Http2Multiplexer.scala
  akka-http2-support/src/main/scala/akka/http/impl/engine/http2/Http2ServerDemux.scala
  akka-http2-support/src/main/scala/akka/http/impl/engine/http2/Http2StreamHandling.scala
Labels: tested

#3508 build: really increase paradox parsing timeout
  build.sbt
  project/ParadoxSupport.scala
Labels: tested

#3509 Prevent scala-steward from updating the akka-http dep
  .scala-steward.conf
Labels: tested

#3512 Fall through on AssertionErrors in testkit (#3400)
  akka-http-testkit/src/main/scala/akka/http/scaladsl/testkit/TestFrameworkInterface.scala
  akka-http-testkit/src/test/scala/akka/http/scaladsl/testkit/ScalatestRouteTestSpec.scala
  akka-http-testkit/src/test/scala/akka/http/scaladsl/testkit/Specs2RouteTestSpec.scala
Labels: tested

#3518 build: update specs2-core from 4.10.3 to 4.10.4
  project/Dependencies.scala
Labels: tested

#3515 build: update caffeine from 2.8.5 to 2.8.6
  project/Dependencies.scala
Labels: tested

#3517 build: update junit from 4.12 to 4.13.1
  project/Dependencies.scala
Labels: tested

#3519 Correctly exclude akka-actor-testkit-typed
  .scala-steward.conf
Labels: tested

#3521 docs: typo fix: "the onne" --> "the one"
  akka-http-core/src/main/resources/reference.conf
Labels: tested

#3520 Remove some minor repetition in HTTP/2 rendering
  akka-http2-support/src/main/scala/akka/http/impl/engine/http2/ResponseRendering.scala
  akka-http2-support/src/main/scala/akka/http/impl/engine/http2/client/RequestRendering.scala
Labels: tested

#3535 http2: use scheme portion of target URI in :scheme pseudo-header
  akka-http2-support/src/main/scala/akka/http/impl/engine/http2/client/RequestRendering.scala
Labels: tested

#3532 http2: protocol-level client specs
  akka-http-core/src/test/scala/akka/http/impl/engine/ws/ByteStringSinkProbe.scala
  akka-http2-support/src/main/scala/akka/http/impl/engine/http2/framing/Http2FrameParsing.scala
  akka-http2-support/src/test/scala/akka/http/impl/engine/http2/HPackSpecExamples.scala
  akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2ClientSpec.scala
  akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2FrameHpackSupport.scala
  akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2FrameProbe.scala
  akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2FrameSending.scala
  akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2ServerSpec.scala
Labels: tested

#3523 http2: test server responses to invalid ping frames
  akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2ServerSpec.scala
Labels: tested

#3526 Move http2 implementation into core
  akka-http-core/src/main/mima-filters/10.2.1.backwards.excludes/remove-Http2Shadow.excludes
  akka-http-core/src/main/scala/akka/http/impl/engine/Http2Shadow.scala
  akka-http-core/src/main/scala/akka/http/impl/engine/http2/BufferedOutletSupport.scala
  akka-http-core/src/main/scala/akka/http/impl/engine/http2/ByteFlag.scala
  akka-http-core/src/main/scala/akka/http/impl/engine/http2/FrameEvent.scala
  akka-http-core/src/main/scala/akka/http/impl/engine/http2/FrameLogger.scala
  akka-http-core/src/main/scala/akka/http/impl/engine/http2/Http2.scala
  akka-http-core/src/main/scala/akka/http/impl/engine/http2/Http2AlpnSupport.scala
  akka-http-core/src/main/scala/akka/http/impl/engine/http2/Http2Blueprint.scala
  akka-http-core/src/main/scala/akka/http/impl/engine/http2/Http2Compliance.scala
  akka-http-core/src/main/scala/akka/http/impl/engine/http2/Http2Multiplexer.scala
  akka-http-core/src/main/scala/akka/http/impl/engine/http2/Http2Protocol.scala
  akka-http-core/src/main/scala/akka/http/impl/engine/http2/Http2ServerDemux.scala
  akka-http-core/src/main/scala/akka/http/impl/engine/http2/Http2SettingsHeader.scala
  akka-http-core/src/main/scala/akka/http/impl/engine/http2/Http2StreamHandling.scala
  akka-http-core/src/main/scala/akka/http/impl/engine/http2/IncomingFlowController.scala
  akka-http-core/src/main/scala/akka/http/impl/engine/http2/PriorityTree.scala
  akka-http-core/src/main/scala/akka/http/impl/engine/http2/ProtocolSwitch.scala
  akka-http-core/src/main/scala/akka/http/impl/engine/http2/RequestParsing.scala
  akka-http-core/src/main/scala/akka/http/impl/engine/http2/ResponseRendering.scala
  akka-http-core/src/main/scala/akka/http/impl/engine/http2/StreamPrioritizer.scala
  akka-http-core/src/main/scala/akka/http/impl/engine/http2/client/RequestRendering.scala
  akka-http-core/src/main/scala/akka/http/impl/engine/http2/client/ResponseParsing.scala
  akka-http-core/src/main/scala/akka/http/impl/engine/http2/framing/FrameRenderer.scala
  akka-http-core/src/main/scala/akka/http/impl/engine/http2/framing/Http2FrameParsing.scala
  akka-http-core/src/main/scala/akka/http/impl/engine/http2/framing/Http2FrameRendering.scala
  akka-http-core/src/main/scala/akka/http/impl/engine/http2/hpack/ByteStringInputStream.scala
  akka-http-core/src/main/scala/akka/http/impl/engine/http2/hpack/HandleOrPassOnStage.scala
  akka-http-core/src/main/scala/akka/http/impl/engine/http2/hpack/HeaderCompression.scala
  akka-http-core/src/main/scala/akka/http/impl/engine/http2/hpack/HeaderDecompression.scala
  akka-http-core/src/main/scala/akka/http/impl/engine/http2/util/AsciiTreeLayout.scala
  akka-http-core/src/main/scala/akka/http/scaladsl/Http.scala
  akka-http-core/src/main/scala/akka/http/scaladsl/model/RequestResponseAssociation.scala
  akka-http-core/src/main/scala/akka/http/scaladsl/model/http2/Http2Exception.scala
  akka-http2-support/src/test/java/akka/http/javadsl/Http2JavaServerTest.java
  akka-http2-support/src/test/scala/akka/http/impl/engine/http2/H2SpecIntegrationSpec.scala
  akka-http2-support/src/test/scala/akka/http/impl/engine/http2/H2cUpgradeSpec.scala
  akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2ClientApp.scala
  akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2ClientServerSpec.scala
  akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2ClientSpec.scala
  akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2FrameSending.scala
  akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2ServerSpec.scala
  akka-http2-support/src/test/scala/akka/http/impl/engine/http2/RequestParsingSpec.scala
  akka-http2-support/src/test/scala/akka/http/scaladsl/Http2BindingViaConfigSpec.scala
  docs/src/main/paradox/compatibility-guidelines.md
  project/Dependencies.scala
Labels: tested

#3541 http2: client: test three consecutive GET requests
  akka-http2-support/src/test/scala/akka/http/impl/engine/http2/HPackSpecExamples.scala
  akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2ClientSpec.scala
Labels: tested

#3548 build: update sbt-mima-plugin from 0.8.0 to 0.8.1
  project/plugins.sbt
Labels: tested

#3547 Add parens to deprecation messages for bind-methods
  akka-http-core/src/main/scala/akka/http/scaladsl/Http.scala
Labels: tested

#3550 build: update specs2-core from 4.10.4 to 4.10.5
  project/Dependencies.scala
Labels: tested

#3537 More accurately track the last-stream-id for GOAWAY
  akka-http-core/src/main/scala/akka/http/impl/engine/http2/Http2ServerDemux.scala
  akka-http-core/src/main/scala/akka/http/impl/engine/http2/Http2StreamHandling.scala
  akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2ClientSpec.scala
Labels: tested

#3559 bench: fix http2 compilation
  akka-http-bench-jmh/src/main/scala/akka/http/impl/engine/http2/H2ServerProcessingBenchmark.scala
Labels: tested

#3561 build: also aggregate akka-http-bench-jmh to fail if benchs fail to compile
  akka-http-bench-jmh/src/main/scala/akka/BenchRunner.scala
  akka-http-bench-jmh/src/main/scala/akka/http/CommonBenchmark.scala
  akka-http-bench-jmh/src/main/scala/akka/http/impl/engine/ConnectionPoolBenchmark.scala
  akka-http-bench-jmh/src/main/scala/akka/http/impl/engine/HeaderParserBenchmark.scala
  akka-http-bench-jmh/src/main/scala/akka/http/impl/engine/HttpEntityBenchmark.scala
  akka-http-bench-jmh/src/main/scala/akka/http/impl/engine/ServerProcessingBenchmark.scala
  akka-http-bench-jmh/src/main/scala/akka/http/impl/engine/StreamServerProcessingBenchmark.scala
  akka-http-bench-jmh/src/main/scala/akka/http/impl/engine/http2/H2ServerProcessingBenchmark.scala
  akka-http-bench-jmh/src/main/scala/akka/http/impl/engine/ws/MaskingBench.scala
  akka-http-bench-jmh/src/main/scala/akka/http/impl/model/parser/UriParserBenchmark.scala
  akka-http-bench-jmh/src/main/scala/akka/http/scaladsl/unmarshalling/sse/LineParserBenchmark.scala
  build.sbt
Labels: tested

#3558 Update to Akka 2.5.32 and fix SocketUtil
  akka-http-core/src/test/scala/akka/http/impl/engine/client/ConnectionPoolSpec.scala
  akka-http-core/src/test/scala/akka/http/scaladsl/ClientServerSpec.scala
  akka-http-core/src/test/scala/akka/http/scaladsl/ClientSpec.scala
  akka-http-core/src/test/scala/akka/http/scaladsl/ClientTransportWithCustomResolverSpec.scala
  akka-http-core/src/test/scala/akka/http/scaladsl/model/EntityDiscardingSpec.scala
  akka-http-core/src/test/scala/akka/testkit/SocketUtil2.scala
  akka-http-tests/src/multi-jvm/scala/akka/http/AkkaHttpServerLatencyMultiNodeSpec.scala
  akka-http-tests/src/test/scala/akka/http/scaladsl/CustomMediaTypesSpec.scala
  docs/src/test/scala/docs/http/scaladsl/server/directives/CustomHttpMethodSpec.scala
  docs/src/test/scala/docs/http/scaladsl/server/directives/TimeoutDirectivesExamplesSpec.scala
  project/AkkaDependency.scala
Labels: tested

#3562 build: exclude akka-http-bench-jmh from whitesource
  build.sbt
Labels: tested

#3554 Adding a few more tests about WINDOW_UPDATE edge cases
  akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2ServerSpec.scala
Labels: tested

#3564 build: disable whitesource for submodules which are not to be published
  build.sbt
  project/Publish.scala
Labels: tested

#3565 docs: add akka-actor-typed dependency to introduction.md
  docs/src/main/paradox/introduction.md
Labels: tested

#3572 build: update sbt-bintray from 0.5.6 to 0.6.0
  project/plugins.sbt
Labels: tested

#3529 http2: send and enforce max concurrent streams setting
  akka-http-core/src/main/resources/reference.conf
  akka-http-core/src/main/scala/akka/http/impl/engine/http2/FrameEvent.scala
  akka-http-core/src/main/scala/akka/http/impl/engine/http2/Http2ServerDemux.scala
  akka-http-core/src/main/scala/akka/http/impl/engine/http2/Http2StreamHandling.scala
  akka-http-core/src/main/scala/akka/http/scaladsl/settings/Http2ServerSettings.scala
  akka-http2-support/src/test/scala/akka/http/impl/engine/http2/H2SpecIntegrationSpec.scala
  akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2FrameProbe.scala
  akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2ServerSpec.scala
Labels: tested

#3577 build: run mima on travis only for master builds or releases
  .travis.yml
Labels: tested

#3579 bench: avoid getting stuck in H2ServerProcessingBenchmark
  akka-http-bench-jmh/src/main/scala/akka/http/impl/engine/http2/H2ServerProcessingBenchmark.scala
Labels: tested

#3552 HTTP/2 unified stream incoming / outgoing stream handling
  akka-http-core/src/main/scala/akka/http/impl/engine/http2/Http2Multiplexer.scala
  akka-http-core/src/main/scala/akka/http/impl/engine/http2/Http2ServerDemux.scala
  akka-http-core/src/main/scala/akka/http/impl/engine/http2/Http2StreamHandling.scala
  akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2ServerSpec.scala
Labels: tested

#3555 http2: disable Push (send SETTING)
  akka-http-core/src/main/scala/akka/http/impl/engine/http2/Http2ServerDemux.scala
  akka-http-core/src/main/scala/akka/http/scaladsl/settings/ClientConnectionSettings.scala
  akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2ClientSpec.scala
  akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2FrameProbe.scala
Labels: needs-attention

#3582 http2: fix Scala 2.12 compilation error
  akka-http-core/src/main/scala/akka/http/impl/engine/http2/Http2ServerDemux.scala
Labels: tested

#3545 http2: remove explicit parallelism parameter in Http2
  akka-http-core/src/main/scala/akka/http/impl/engine/http2/Http2.scala
  akka-http-core/src/main/scala/akka/http/scaladsl/Http.scala
Labels: tested

#3581 Respect remote max concurrent streams (reprise)
  akka-http-core/src/main/scala/akka/http/impl/engine/http2/Http2Multiplexer.scala
  akka-http-core/src/main/scala/akka/http/impl/engine/http2/Http2Protocol.scala
  akka-http-core/src/main/scala/akka/http/impl/engine/http2/Http2ServerDemux.scala
  akka-http-core/src/main/scala/akka/http/impl/engine/http2/Http2StreamHandling.scala
  akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2ClientSpec.scala
  akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2ServerSpec.scala
Labels: tested

#3583 Helper to expect a parsed frame of a given type
  akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2ClientSpec.scala
  akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2FrameProbe.scala
  akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2ServerSpec.scala
Labels: tested
