Repository akka/akka-http, pull requests merged in 2020-12, with the labels that each got.

#3665 Akka HTTP BOM
  build.sbt
  project/plugins.sbt
Labels: tested

#3671 http2: handle RST while sending data + more tests
  akka-http-core/src/main/scala/akka/http/impl/engine/http2/Http2StreamHandling.scala
  akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2ClientSpec.scala
  akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2ServerSpec.scala
Labels: tested

#3672 http2: 'pull' was lost when closing while waiting for window
  akka-http-core/src/main/scala/akka/http/impl/engine/http2/Http2Multiplexer.scala
  akka-http-core/src/main/scala/akka/http/impl/engine/http2/Http2StreamHandling.scala
  akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2ClientSpec.scala
Labels: tested

#3681 docs: Link project info to snapshots
  project/project-info.conf
Labels: t:docs, tested

#3676 Test coverage for request HTTP2 client entity stream failing
  akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2ClientSpec.scala
Labels: tested

#3683 http2: check all stages are stopped in client tests
  akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2ClientSpec.scala
Labels: tested

#3694 FutureDirectivesExampleSpec fail fix
  docs/src/test/scala/docs/http/scaladsl/server/directives/FutureDirectivesExamplesSpec.scala
Labels: tested

#3697 build: update paradox-theme-akka, ... from 0.35 to 0.36
  project/plugins.sbt
Labels: tested

#3691 Avoid temporaryServerHostnameAndPort
  akka-http-core/src/test/scala/akka/http/impl/engine/client/ConnectionPoolSpec.scala
  akka-http-core/src/test/scala/akka/http/scaladsl/ClientServerSpec.scala
  akka-http-core/src/test/scala/akka/http/scaladsl/ClientSpec.scala
  akka-http-core/src/test/scala/akka/http/scaladsl/ClientTransportWithCustomResolverSpec.scala
  akka-http-core/src/test/scala/akka/http/scaladsl/model/EntityDiscardingSpec.scala
  akka-http-tests/src/test/scala/akka/http/scaladsl/CustomMediaTypesSpec.scala
  docs/src/test/scala/docs/http/scaladsl/server/directives/CustomHttpMethodSpec.scala
Labels: tested

#3695 build: update jackson-databind from 2.10.5 to 2.10.5.1
  build.sbt
  docs/src/main/paradox/common/xml-support.md
  project/Dependencies.scala
Labels: 2 - pick next, tested

#3657 http2: extract common rendering + add userAgent on requests
  akka-http-core/src/main/scala/akka/http/impl/engine/http2/Http2Blueprint.scala
  akka-http-core/src/main/scala/akka/http/impl/engine/http2/Http2StreamHandling.scala
  akka-http-core/src/main/scala/akka/http/impl/engine/http2/HttpMessageRendering.scala
  akka-http-core/src/main/scala/akka/http/impl/engine/http2/ResponseRendering.scala
  akka-http-core/src/main/scala/akka/http/impl/engine/http2/client/RequestRendering.scala
  akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2ClientSpec.scala
  akka-http2-support/src/test/scala/akka/http/impl/engine/http2/HttpMessageRenderingSpec.scala
Labels: tested

#3660 core: allow illegal header keys to be ignored #3133
  akka-http-core/src/main/mima-filters/10.2.1.backwards.excludes/issue-3133-ignore-illegal-header-names.excludes
  akka-http-core/src/main/resources/reference.conf
  akka-http-core/src/main/scala/akka/http/impl/engine/parsing/HttpHeaderParser.scala
  akka-http-core/src/main/scala/akka/http/impl/model/parser/HeaderParser.scala
  akka-http-core/src/main/scala/akka/http/impl/settings/ParserSettingsImpl.scala
  akka-http-core/src/main/scala/akka/http/javadsl/settings/ParserSettings.scala
  akka-http-core/src/main/scala/akka/http/scaladsl/settings/ParserSettings.scala
  akka-http-core/src/test/scala/akka/http/impl/engine/client/LowLevelOutgoingConnectionSpec.scala
  akka-http-core/src/test/scala/akka/http/impl/engine/parsing/HttpHeaderParserSpec.scala
Labels: tested

#3698 Add 10.2.2 release notes
  docs/src/main/paradox/release-notes/10.2.x.md
Labels: tested

#3700 Check mima against 10.2.2
  project/MiMa.scala
Labels: tested

#3699 Small release checklist updates
  scripts/release-train-issue-template.md
Labels: tested

#3696 build: update caffeine from 2.8.6 to 2.8.7
  project/Dependencies.scala
Labels: tested

#3675 build: update github-api from 1.116 to 1.117
  project/plugins.sbt
Labels: tested

#3682 docs: show akka-http-bom in dependencies
  docs/src/main/paradox/common/caching.md
  docs/src/main/paradox/common/json-support.md
  docs/src/main/paradox/common/xml-support.md
  docs/src/main/paradox/compatibility-guidelines.md
  docs/src/main/paradox/introduction.md
  docs/src/main/paradox/routing-dsl/directives/caching-directives/index.md
  docs/src/main/paradox/routing-dsl/testkit.md
  docs/src/main/paradox/server-side/http2.md
Labels: t:docs, tested

#3649 build: update sbt from 1.3.13 to 1.4.4
  project/build.properties
Labels: tested

#3704 Revert "build: update sbt from 1.3.13 to 1.4.4"
  project/build.properties
Labels: tested

#3678 Fail if trying to bind flow/source with HTTP2
  akka-http-core/src/main/scala/akka/http/scaladsl/Http.scala
Labels: tested

#3705 Content-Disposition filename encoding fix #1240
  akka-http-core/src/main/scala/akka/http/impl/model/parser/CharacterClasses.scala
  akka-http-core/src/main/scala/akka/http/impl/model/parser/ContentDispositionHeader.scala
  akka-http-core/src/main/scala/akka/http/impl/util/Rendering.scala
  akka-http-core/src/main/scala/akka/http/scaladsl/model/headers/headers.scala
  akka-http-core/src/test/scala/akka/http/impl/model/parser/HttpHeaderSpec.scala
Labels: tested

#3711 Add scaladoc for path.?/
  akka-http-core/src/main/scala/akka/http/scaladsl/model/Uri.scala
Labels: tested
