Repository akka/akka-http, pull requests merged in 2021-04, with the labels that each got.

#3793 Include port in HTTP/2 binding warning
  akka-http-core/src/main/scala/akka/http/scaladsl/Http.scala
Labels: tested

#3792 build: publish to sonatype directly
  .travis.yml
  build.sbt
  project/Formatting.scala
  project/Publish.scala
  project/plugins.sbt
  scripts/release-train-issue-template.md
Labels: tested

#3539 build: replace jabba by proper debian installation
  .travis.yml
Labels: validating

#3802 build: make sure launcher is downloaded from correct repo
  .travis.yml
Labels: needs-attention

#3801 Merge pull request #3801 from jrudolph/publish-to-sonatype-directly-10.1
  .travis.yml
  build.sbt
  project/Formatting.scala
  project/Publish.scala
  project/plugins.sbt
  scripts/release-train-issue-template.md
Labels: tested
